### DISCUSSION TITLE
The use of $URL variable

### DISCUSSION THREAD

**Discussion by hmp3094** [release-drafter/release-drafter#1006] [Q&A]
I have included the $URL as follows: change-template: '* $TITLE $URL @$AUTHOR'.
I want the change in the release draft to include the URL as it is and not as a hyperlink in the PR number. Even after replacing #$NUMBER with $URL, it is displaying the change as "TITLE #PR_No. (with a hyperlink to the PR) @AUTHOR 

Not sure what I am doing wrong. Please advise!

**Comment by jetersen** [comment]
Can you share your config or even better a link to the config?

**Comment by hmp3094** [comment]
I can't share a link because it's on a self hosted github but here is my config.

```
categories:
  - title: '🚀 Features'
    label: 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🔼 Enhancements'
    label: 'enhancement'

change-template: '* $TITLE ($URL) @$AUTHOR'

template: |
  ## Changes
  $CHANGES
```

I noticed that when I try to publish the release, it displays just the URL. But that's only when you are on the edit draft page, not when you are just viewing the draft in the releases section. The reason for having the URL in the change is that someone else is going to copy the draft and paste it on some other document that's not on github.
