### DISCUSSION TITLE
Excluding my own user

### DISCUSSION THREAD

**Discussion by evertramos** [release-drafter/release-drafter#1042] [Q&A] [answered]
I have tried to use the 'exclude-contributors' option as mentioned in the docs:

[exclude-contributors](https://github.com/release-drafter/release-drafter#exclude-contributors)

But it did not work for my user, I add the option to my 'release-drafter.yml', as of:

```yml
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
exclude-contributors:
  - 'evertramos'
```

[my current release drafer.yml](https://github.com/evertramos/basescript/blob/cd52b5127327c42a054a9d45f5d3ca05e8a4c508/.github/release-drafter.yml#L17)

But still brings my user as contributor:

[release v0.2.1 - generated by release-drafter](https://github.com/evertramos/basescript/releases/tag/v0.2.1)

Am I missing something here?
