### DISCUSSION TITLE
Help needed with publishing a release when pushed to master

### DISCUSSION THREAD

**Discussion by dreinon** [release-drafter/release-drafter#1145] [Q&A] [answered]
Hi!
My current workflow is merging different feat, fix, etc, PR's into develop and then, when I want to release a new version, opening and merging a PR from develop to master, which will deploy to production, bump project's version (npm) and make a github release, using semantic-version, which uses commit messages to generate the changelog.

I would like to use release drafter to be able to use PR names. I have the release drafter config set up, but have doubts on how to do all the release process when merging from develop to master. My idea is:
- PR merged into develop:
    - creates/updates draft release according to labels (btw, using autolabeler)
- PR merged from develop into master:
    - this PR doesn't get added to draft release (autolabeler marks PRs from develop branch as skip-changelog, which are excluded)
    - bump project's version (npm) and commit changes (*)
    - execute release drafter to publish draft release (*)

I have doubts on how to do the steps marked as (*). Since release-drafter is responsible to resolve the new version based on semver, but the github release should be published after the project's version is bumped in order to include the bump commit.

Thanks!

Release Drafter Config
```yml
name-template: 'v$RESOLVED_VERSION 🌈'

tag-template: 'v$RESOLVED_VERSION'

categories:
    - title: '🚀 Features'
      labels: 'feature'

    - title: '✨ Improvements'
      labels: 'improvement'

    - title: '🐎 Performance'
      labels: 'performance'

    - title: '🔨 Refactor'
      labels: 'refactor'

    - title: '🐛 Bug Fixes'
      labels: 'bug'

    - title: '🧰 Maintenance'
      label: 'chore'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

change-title-escapes: '\<*_&'

version-resolver:
    major:
        labels:
            - 'major'

    minor:
        labels:
            - 'feature'
            - 'improvement'

    patch:
        labels:
            - 'chore'
            - 'fix'
            - 'performance'
            - 'refactor'

    default: patch
replacers:
    - search: '/(build|chore|ci|docs|feat|fix|improve|perf|refactor|revert|style|test)(\(\w+\)?((?=:\s)|(?=!:\s)))?(!)?(:)(\s.*)/g'
      replace: '$2$6'

autolabeler:
  - label: 'chore'
    title:
      - '/chore/i'

  - label: 'bug'
    title:
      - '/fix/i'

  - label: 'feature'
    title:
      - '/feat/i'

  - label: 'refactor'
    title:
      - '/refactor/i'

  - label: 'improvement'
    title:
      - '/improve/i'

  - label: 'refactor'
    title:
      - '/refactor/i'
  
template: |
    ## What's Changed

    $CHANGES
```
