### DISCUSSION TITLE
Reasons PRs don't get labelled?

### DISCUSSION THREAD

**Discussion by edalzell** [release-drafter/release-drafter#1171] [Q&A]
I am trying to get rid of extra actions, so I'd like to have release drafter label the PRs, but I can't seem to get it to work.

Here's my config file:
```yaml
name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 New'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Fixed'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
autolabeler:
  - label: 'chore'
    branch:
      - '/docs{0,1}\/.+/'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
template: |
  ## Changes

  $CHANGES
```

and here's the action:
```yaml
name: Release Drafter

on:
  pull_request:
    types: [closed]
permissions:
  contents: read

jobs:
  update_release_draft:
    if: github.event.pull_request.merged == true
    permissions:
      contents: write  # for release-drafter/release-drafter to create a github release
      pull-requests: write  # for release-drafter/release-drafter to add label to PR
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

What am I doing wrong? No PRs are labelled.
