### DISCUSSION TITLE
[Q]: "released" trigger is never fired when using recommended release drafter

### DISCUSSION THREAD

**Discussion by stevenengland** [release-drafter/release-drafter#1318] [Q&A]
Hi at all,

I currently use release drafter to publish releases like this:

      - name: Publish the release notes
        uses: release-drafter/release-drafter@v5.22.0
        with:
          publish: ${{ steps.check-version.outputs.tag != '' }}
          tag: ${{ steps.check-version.outputs.tag }}
          config-name: release_drafting_config.yml
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

As a result the release is published. But that does not trigger the "released" event to use that for another workflow.

The other workflow is this:

```
---
name: Changelog Updating

"on":
  release:
    types: [released]

jobs:
  update:
    name: Update Changelog
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.target_commitish }}
    ...
```
This workflow is never started although I had new releases in the meanwhile. Do you have any idea what to check? 

Thanks!

**Comment by harm-matthias-harms** [comment]
If anybody drops by: Here is written why it's not working and how to fix it: https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/making-authenticated-api-requests-with-a-github-app-in-a-github-actions-workflow

**Comment by jetersen** [comment]
```yaml
"on":
  release:
    types: [released]
```
The correct type to use is `published` That includes the necessary tags.
