### DISCUSSION TITLE
Release / Release Configuration based on Branch?

### DISCUSSION THREAD

**Discussion by ekristen** [release-drafter/release-drafter#1332] [Q&A] [answered]
Lets say for example the primary release branch is `main` and it's tagged a 2.1.0 but you have a `release/1.x` (at 1.5.1) for putting any hotfixes or back ports into.

Is there a way to have release-drafter automatically tag/release changes made to `main` on the 2.1.0 semver path and then have any merges into `release/1.x` trigger the next semver on the 1.5.1 path?

**Comment by jetersen** [comment]
Check the README.

We have commitish and filter-by-commitish and commitish can be applied via github action:
https://github.com/release-drafter/release-drafter/blob/569eb7ee3a85817ab916c8f8ff03a5bd96c9c83e/action.yml#L41-L45

**Reply by ekristen** [reply]
I've read it, it didn't appear to be what I wanted, I don't want to have to specify the exact commitish but are you saying if I specify the branch as the commitish it will automatically determine if 1.x or 2.x was on the branch last and tag the next iteration appropriately?

Perhaps I didn't ask or explain things as clearly as I was wanting to. I'm using release-drafter in an automated way, each commit to main automatically creates a new semver based on the default configuration or labels, so each time a commit hits main and the last semver was 1.2.3 and the default is patch, then 1.2.4 becomes the next automatically created by release-drafter.

When I move onto 2.0 on the main branch, I create branch release/1.x, I want any commit hitting release/1.x to go to 1.2.5 or 1.3.0 and any commit going to main branch going to 2.0.1 or 2.1.0.

**Reply by jetersen** [reply]
That's basically what commitish does. You point to a branch and it calculates based on that at long as you set filter by commitish to true

**Reply by ekristen** [reply]
ok great! thanks for confirming that behavior.

**Reply by ekristen** [reply]
That is not what just happened. I set commitish to `release/1.x` and the filter setting to true and it created a tag on 2.x instead of 1.x

**Reply by ekristen** [reply]
Fetching parent commits of refs/heads/release/1.x since 2023-02-16T14:55:10Z -- the last tag was on 11/3/2022, could that be why? It's not looking far enough back? 

```
Thu Nov 3 11:20:48 2022 -0400 fbacb2d (HEAD -> release/1.x, tag: 0.2.43, origin/release/1.x,) Merge pull request ...
```

**Reply by ekristen** [reply]
I've tried a few different things, even when this runs on the release/1.x it ultimately creates a change log off the default branch instead of the release/1.x branch. I'm using the github action. 

```
name: auto-release

on:
  push:
    branches:
      - main
      - "release/*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          publish: true
          prerelease: false
          config-name: auto-release.yml
        env:
          GITHUB_TOKEN: ${{ token }}
```

```
commitish: release/1.x
filter-by-commitish: true

name-template: "v$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
version-template: "$MAJOR.$MINOR.$PATCH"
```

**Reply by jetersen** [reply]
It reads the config from the default branch so you cannot push the commitish into the config file. You need to supply it from github actions with block.

using:

```yaml
with:
  ...
  commitish: ${{ github.ref }}
```
