### DISCUSSION TITLE
Question regarding regex/branches

### DISCUSSION THREAD

**Discussion by H4ppy-04** [release-drafter/release-drafter#1343] [Q&A]
Hi Release Drafter Team and Community,

**Goal**
I want to be able to run release drafter on release branches.

**Problem Description**
I'm wondering if it's at all possible to use a wildcard character when specifying a branch name to operate on. 

**Problem Example**
For example, in my scenario I want `release-drafter` to only run on branches that have a format that follows a semantic convention such as x.y.z where x y and z are numbers.

**What I've tried**
I've tried to implement this as follows:
```yaml
name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - [0-9].[0-9].[0-9]
```
> Along with trying an assortment of regex expressions, I can't seem to get anything to work.

**Final summary**
I'm wondering if this is even at all possible? Thank you for your time and consideration.

Kind Regards,
Joshua.
