### DISCUSSION TITLE
How do you make a major or minor release draft that includes many PR?

### DISCUSSION THREAD

**Discussion by arashi-dev** [release-drafter/release-drafter#1367] [Q&A] [answered]
Currently, I am not using this project but I may use it in my next project. And I have a question

I see many release drafts in this repo that have many PR names inside of them. how is that possible? what is the logic behind it?

**Comment by arashi-dev** [comment]
Oh, my bad,
I thought this project also bumps the app version automatically based on the PR. but it doesn't, right? this repo, creates release drafts when the version of package.json is bumped, and it will include all the changes (PRs) between the last version and the current version, yes?

**Comment by jetersen** [comment]
Here is a YouTube video that explains most of release drafter.
https://www.youtube.com/watch?v=EBmcx_gAts8

What you are looking for is to combine multiple actions to solve your need.
Take a look at the workflows in many of the repos that use release-drafter or look at our workflows:

https://github.com/release-drafter/release-drafter/blob/master/.github/workflows/release.yml
That workflow is based on us doing a `yarn version minor` which does a git push based on the npm [postversion scripts](https://github.com/release-drafter/release-drafter/blob/09c613e259eb8d4e7c81c2cb00618eb5fc4575a7/package.json#L18)

This search find users of release drafter: https://github.com/search?q=release-drafter%2Frelease-drafter%20path%3A.github%2Fworkflows&type=code

**Reply by arashi-dev** [reply]
Thank you for your response. I used it in my project and it's working now!

But there is an issue! I have both `draft.yml` and `release.yml` files in the workflows directory (copied from this repo and removed extra steps inside `release.yml`).
the issue is that when I bump the version using `pnpm version prerelease`, the release draft gets published but its title is `unstaged-xxx` with the same tag name. I also saw the related issues on this repo but I couldn't find how to solve it.

here are my configs:

###### .github/workflows/draft.yml
```yml
name: Release Drafter

on:
  push:
    branches:
      - main

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitish: main
```

###### .github/workflows/release.yml
```yml
name: Release
on:
  push:
    tags:
      - v*.*.*

env:
  HUSKY: "0"

jobs:
  build:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: version
        id: version
        run: |
          tag=${GITHUB_REF/refs\/tags\//}
          version=${tag#v}
          echo "version=${version}" >> $GITHUB_OUTPUT

      - uses: release-drafter/release-drafter@master
        with:
          version: ${{ steps.version.outputs.version }}
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

###### package.json
```json
"version": "0.0.1-pre-alpha.13",
"scripts": {
    "postversion": "git push && git push --tags"
}
```

the file `.github/release-drafter.yml` is the same as this repo

and here is what I do:
1. create a new branch and commit some changes
2. make a PR and merge it
3. pull the changes from `main` and run `pnpm version prerelease`

**Reply by jetersen** [reply, marked as answer]
You need to use the config file and input parameters to solve your use case. Please check the readme for configuration options and input options

**Reply by arashi-dev** [reply]
Fixed it! As you said, I had to add `tag` and `name` options in the `release.yml`

```yml
with:
    name: v${{ steps.version.outputs.version }}
    tag: v${{ steps.version.outputs.version }}
    version: ${{ steps.version.outputs.version }}
    publish: true
```

thanks for the help and the project :)
