### DISCUSSION TITLE
Unexpected pre-release draft, major number not increased

### DISCUSSION THREAD

**Discussion by hlecnt** [release-drafter/release-drafter#1393] [Q&A]
Hello release-drafter Team.

First of all, thank you for your job!

I'm facing an unexpected behavior in draft pre-release version resolution. I didn't find an anwser in the README so I'm asking it here.

The latest release of my project is 3.3.1, I've added some features to the develop branch and release-drafter prepared the pre-release draft version 3.3.2-rc.0, that's just fine and I've published this pre-release.

Then, I've pushed a breaking feature. I was expecting release-drafter to resolve a new pre-release draf like this 4.0.0-rc.0 but it resolves 3.3.2-rc.1

I had to delete both pre-release 3.3.2-rc0 and pre-release draft 3.3.2-rc.1 then restart manually release-drafter to have the 4.0.0-rc.0 as pre-release draft created by release-drafter.

Lables are correctly set on the pull requests.

**Is it the expected behavior ?**

I'm using release-drafter v6.

Here is the configuration I'm using:

```
name-template: "$RESOLVED_VERSION 🔖"
tag-template: "$RESOLVED_VERSION"
categories:
  - title: "✨ Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🧰 Maintenance"
    label: "chore"
  - title: "⬆️ Dependencies"
    collapse-after: 3
    labels:
      - "dependencies"
autolabeler:
  - label: "chore"
    branch:
      - '/misc\/.+/'
      - "/revert.+/"
  - label: "bugfix"
    branch:
      - '/bugfix\/.+/'
  - label: "feature"
    branch:
      - '/feature\/.+/'
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
exclude-labels:
  - "skip-changelog"
version-resolver:
  major:
    labels:
      - "breaking"
      - "design"
  minor:
    labels:
      - "feature"
      - "enhancement"
  patch:
    labels:
      - "chore"
      - "dependencies"
  default: patch
template: |
  ## Changes

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...$RESOLVED_VERSION
```

BR,
