### DISCUSSION TITLE
The release-drafter version 6 appears to function differently compared to the version 5 with multiple config-name's

### DISCUSSION THREAD

**Discussion by amakitaipale** [release-drafter/release-drafter#1435] [Q&A]
Hey there! I’m super new to `release-drafter`, and I know this might sound like a silly or more like a stupid question, but I’m having a bit of trouble. I’m using version `5.25.0`, and everything works great. But when I try to use it with my monorepo with `v6`, I get this error: `Error: Unable to resolve action .github/release-drafter@v6, action not found`. Still the first job on yml-file runs just great and succesfully. I’ve heard that multiple `config-name` should be a “workaround, for multirepos”, but I’m not sure how to use it. Any help would be greatly appreciated!  I just want to say that this is a superb action.  ❤️ 

## .github/workflows/release-drafter.yml

```
jobs:               
    multirepo1-release-drafter:
      name: '[multirepo1] Draft release'
      runs-on: ubuntu-latest
      steps:
        - uses: release-drafter/release-drafter@v5.25.0
          with:
            config-name: release-drafter-multirepo1.yml
            disable-autolabeler: true
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    multirepo2-release-drafter:
      name: '[multirepo2] Draft release'
      runs-on: ubuntu-latest
      steps:
        - uses: release-drafter/release-drafter@v5.25.0
          with:
            config-name: release-drafter-multirepo2.yml
            disable-autolabeler: true
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
````
## .gitbub/release-drafter-multirepo1.yml e.g.

```
_extends: release-drafter.yml
name-template: 'multirepo1v$RESOLVED_VERSION'
tag-template: 'multirepo1-v$RESOLVED_VERSION'
tag-prefix: multirepo1-v
include-paths:
  - "apps/multirepo1/"
 ```

(Stupid) Question 2: Handling New Configuration Files During Repository Merges:

When merging a new multirepo into your repository, you may encounter an issue where the branch or pull request contains a new configuration file (`config-name`) for the merged repository. In our case, we are merging to the `main` branch.

I have encountered an error that serves as a workaround for this issue. However, I am seeking a more permanent solution to this problem.

`stack: 'Error: Configuration file .github/release-multirepo3.yml is not found. The configuration file must reside in your default branch.\n' +`

I’m a bit confused about why version 5 works but version 6 doesn’t. I’ve looked through the documentation, but I couldn’t find any explanation. Could you please help me out? I’d really appreciate it if anyone whould have time and patience 🙏 

By the way, I’d like to express my gratitude to this [discussion](https://github.com/release-drafter/release-drafter/issues/469) and the [example](https://github.com/guardrail-dev/guardrail/blob/master/.github/workflows/release-drafter.yml) mentioned on the thread. They really helped me understand how to get did this far.
