### ISSUE TITLE
Error applying minor version label

### ISSUE THREAD

**Issue by KevinBatdorf** [release-drafter/release-drafter#1011]
Got an error when the workflow had a `minor` label applied

![Screen Shot 2022-01-13 at 12 13 55 PM](https://user-images.githubusercontent.com/1478421/149377119-1dd88094-c112-458a-b48a-9fbb62e6d897.png)

```
name: Draft Release
on:
    push:
        branches:
            - main
        pull_request:
            types: [opened, reopened, synchronize]

jobs:
    update_release_draft:
        runs-on: ubuntu-latest
        steps:
            - uses: release-drafter/release-drafter@v5
              with:
                  config-name: release-template.yml
              #   disable-autolabeler: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```

```
name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
categories:
    - title: "🚀 What's new"
      labels:
          - 'PR: New'
    - title: '🏋️ Improvements'
      labels:
          - 'PR: Improvement'
    - title: '🐛 Bug Fixes'
      labels:
          - 'PR: Fix'
exclude-labels:
    - 'PR: No Changelog'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
    minor:
        labels:
            - 'minor'
    patch:
        labels:
            - 'patch'
    default: patch
template: |
    ## Release Changes

    $CHANGES

```

I have a general question to. If we add a `minor` label to multiple PRs will it continuously bump the version number? Or is it only one bump per release? Thanks
