### ISSUE TITLE
autolabeler needs on option to stop labeling on match (break on match)

### ISSUE THREAD

**Issue by ssbarnea** [release-drafter/release-drafter#1022]
I observed that is almost impossible to prevent multiple label matches, regardless how well you try to define the matching patterns. This does not play well with labels that are supposed to be exclusive, like being a bug or a feature or  something to be excluded from the changelog.

Lucky for us the current configuration format is using sequence of objects for labeling, making it very easy to implement a break on match option for labels.

Basically by adding an option that tells labeler to stop finding other labels to add to the pull request when current pattern is matched we can prevent duplicates.

Using this we can put all labels that do not have conflicts at the top of the sequence and after them start adding labels with `stop_on_match: true` at the bottom.

**Comment by jetersen** [comment]
Isn't this just basic regex?

`/a/` should only match the first occurrence.
`/a/g` should match all the occurrences.

**Comment by ssbarnea** [comment]
@jetersen I think I may not expressed it well enough. Take a look at https://github.com/ansible-community/devtools/blob/main/.github/release-drafter.yml#L47-L62 

The issue is that release-drafter is looping on all label-match configs and is not able to stop if one label match was found. You endup having more labels added than you want, basically due to overlapping on other match conditions, something that cannot always be avoided.

The workaround would be have something like:
```yaml
autolabeler:
  - label: 'foo'
     ...
     stop_on_match: true

  - label: 'bar' # that label will never be added if `foo` was already found as matching due to stop_on_match
     ...
```
