### ISSUE TITLE
Can't we put the "number dot" as prefix?

### ISSUE THREAD

**Issue by AsheKR** [release-drafter/release-drafter#1024]
Can't i put numbers in the name-template?

v.1.3.6.3 -> v1.1.3.7

![image](https://user-images.githubusercontent.com/42999044/149946810-6b8d1d81-64b4-417d-bc29-50ed158d2ad6.png)

```yml
# Release drafter configuration https://github.com/release-drafter/release-drafter#configuration
# Emojis were chosen to match the https://gitmoji.carloscuesta.me/

name-template: "v1.$NEXT_PATCH_VERSION"
tag-template: "v1.$NEXT_PATCH_VERSION"

categories:
  - title: ":rocket: Features"
    labels: [enhancement, feature]
  - title: ":wrench: Fixes & Refactoring"
    labels: [bug, refactoring, bugfix, fix]
  - title: ":package: Build System & CI/CD"
    labels: [build, github_actions, testing]
  - title: ":boom: Breaking Changes"
    labels: [breaking]
  - title: ":pencil: Documentation"
    labels: [documentation]
  - title: ":fairy: Maintenance"
    labels: [chore]
  - title: ":arrow_up: Dependencies updates"
    labels: [dependencies]

template: |
  ## What’s Changed

  $CHANGES

  $CONTRIBUTORS

```
