### ISSUE TITLE
$RESOLVED_VERSION not expanded when set via action input

### ISSUE THREAD

**Issue by mkurz** [release-drafter/release-drafter#1048]
Using the `name` input:
```yml
...
jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          name: "$RESOLVED_VERSION"
...
```
the release draft will be named `$RESOLVED_VERSION`, which obviously is not what I expected.

However inside the config file
```
name-template: '$RESOLVED_VERSION'
```
the release draft will correctly be named with the version, e.g. `1.0.0`.

Now, the `name` overrides the `name-template`:
<kbd><img width="800" src="https://user-images.githubusercontent.com/644927/151940732-1d15cfae-778f-4564-9a7d-fd506dc809b9.png" /></kbd>

I expect both configs behave identically, I would have guessed variable expansion takes places after the override happened, so it shouldn't matter where the config string came from.

**Comment by jetersen** [comment]
Maybe but what's wrong with using name-template?

**Comment by mkurz** [comment]
Nothing wrong with using `name-template`, however I am setting up a generic release draft in our org's `.github` repo and in various other repos I set up workflows that reference that `base.yml` drafts, and want to pass use the specific project name as title of the release.
For example:
repoA has the workflow:
```yml
...
        with:
          name: "Project A $RESOLVED_VERSION"
...
```
repoB has the workflow
```yml
...
        with:
          name: "Project B $RESOLVED_VERSION"
...
```
BTW: I tried to achieve that with env variables, by passing the project name to the base file, but that doesn't working (#847). Actually for our needs using `$RESOLVED_VERSION` would be enough.
