### ISSUE TITLE
PRs merged in master branch appearing in the draft when 'develop' is specified

### ISSUE THREAD

**Issue by ClaudiaCF** [release-drafter/release-drafter#1064]
I have the configuration files in my default branch (master) with 'develop' specified as branch to trigger the release drafter when merging the PRs:
```
on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - develop
```
Every PR that is merged to develop appears okay but some PR's that are merged to both develop and master (hotfixes) are appearing those two times while I was expecting that it would only appear the one merged to develop. Any idea of what could be happening?
