### ISSUE TITLE
When publish: true how to make it to auto-publish to Market place in case of a GitHub Action

### ISSUE THREAD

**Issue by cytopia** [release-drafter/release-drafter#1076]
I have enabled `publish:true` so that upon merge to master, the release is automatically created with a tag. You can see that in release `0.4.4`. However it is missing the `Marketplace` indicator as shown in release `0.4.3` (which I've published manually).

![Screenshot 2022-02-18 12-58-27  selection](https://user-images.githubusercontent.com/12533999/154679083-7746e8ff-fc2e-44ba-a705-7b68443255b3.png)

When I publish a release manually it looks like this: 

![Screenshot 2022-02-18 12-58-38  selection](https://user-images.githubusercontent.com/12533999/154679294-d15a6adb-3278-44a3-88f6-668820bd70d4.png)

**Question:** So how can I make release drafter to also publish this action upon creation of a new release?

**Comment by kigary** [comment]
Hi. @cytopia. I have searched all issues, read source codes of release-drafter and couldn't find answer to my question and found your opened issue here. Assuming from your description that you have successfully configured your release-drafter to publish release. In my case release-drafter is not publishing release, just creating draft release. Wasn't able to achieve publish with release-drafter. Can you please share your config or help to debug the issue? Attaching bellow my config:

```
name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bugfix'
      - 'hotfix'
  - title: '🧰 Maintenance'
    labels: 
      - 'refactor'
      - 'enhancement'
  - title: '📃 Documentation'
    label: 'documentation'
exclude-labels:
  - 'skip-changelog'
replacers:
  - search: '/FN-(\d{1,4})/g'
    replace: '[FN-$1](https://betconstruct.atlassian.net/browse/FN-$1)'
autolabeler:
  - label: 'bugfix'
    branch:
      - '/bugfix\/.+/'
  - label: 'hotfix'
    branch:
      - '/hotfix\/.+/'
  - label: 'enhancement'
    branch:
      - '/enhancement\/.+/'
  - label: 'refactor'
    branch:
      - '/refactor\/.+/'
  - label: 'feature'
    branch:
      - '/feature\/.+/'
  - label: 'release'
    branch:
      - '/release\/.+/'
  - label: 'experimental'
    branch:
      - '/experimental\/.+/'
  - label: 'skip-changelog'
    branch:
      - '/(main|develop|experimental).*/'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'release'
  patch:
    labels:
      - 'hotfix'
publish: true
latest: true
template: |
  ## Changes

  $CHANGES
change-template: '* $TITLE'
```
