### ISSUE TITLE
Autolabeler seems to fail when sublabels exist

### ISSUE THREAD

**Issue by johnnywang** [release-drafter/release-drafter#1098]
A question about how autolabeler works, that may also be an actual issue. I had previously set up autolabeler to work in our monorepo, and labels were getting applied correctly based on title regex and file paths. However, after someone added some sublabels, the autolabeling seems to have stopped working, which has me wondering if autolabeler will fail if the specified label might have multiple prefix matches?

As an example, we have the following rule specified:

```
  - label: 'mobile'
    files:
      - '/js/projects/platform-mobile/**/*'
    title:
      - '/\[(platform-)?mobile\]/i'
```

This was working fine when we only had a `mobile` label, but seems to have stopped autolabeling after the addition of `mobile/fix`, `mobile/feature`, etc labels
