### ISSUE TITLE
Autolabeler question

### ISSUE THREAD

**Issue by thedmeyer** [release-drafter/release-drafter#1111]
I am a bit confused as to how the autolabeler functions.

Let's say I have changes on the main branch (that camr through feature branches as PRs), and I have an open PR that I am about to merge from the main branch to the prod branch.

Does the autolabeler label all previous PRs that went into main upon push to prod via this PR?

I am envisioning a system that drafts a release upon push of this PR to prod. Is this correct?

Thanks for the help

**Comment by cchanche** [comment]
Autolabeller does not scan for PR on it's own - it relies on the Github Action's context paylaod - meanin it'll only label the pr a particular workflow is running for.

> I am envisioning a system that drafts a release upon push of this PR to prod. Is this correct?

You'd have to run :

```yaml
name: Auto Label

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - 'prod'

permissions:
  contents: read

jobs:
  auto_label:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter/autolabeler@v7
```
... to label your PR(s) on `prod`, and :

```yaml
name: Release Drafter

on:
  push:
    branches:
      - prod

# Permissions for default token (secrets.GITHUB_TOKEN)
permissions:
  contents: write
  pull-requests: read

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v7
```

... to update a draft when prod is updated.
