### ISSUE TITLE
ERROR: Validation Failed: {"resource":"Release","code":"invalid","field":"target_commitish"}

### ISSUE THREAD

**Issue by sumanth-sure** [release-drafter/release-drafter#1125]
Hi support,

I am not able to get the release tag value from release drafter. I have the following error message in github action
 
```
Validation Failed: {"resource":"Release","code":"invalid","field":"target_commitish"}
{
  name: 'HttpError',
  id: '2187790795',
  status: 422,
  response: {
    url: 'https://********/releases/64928231',
    status: 422,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      connection: 'close',
      'content-length': '193',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Thu, 21 Apr 2022 07:24:06 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'GitHub.com',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-accepted-oauth-scopes': 'repo',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-media-type': 'github.v3; format=json',
      'x-github-request-id': '*****:62610696',
      'x-oauth-scopes': 'repo, write:packages',
      'x-ratelimit-limit': '5000',
      'x-ratelimit-remaining': '4964',
      'x-ratelimit-reset': '1650528337',
      'x-ratelimit-resource': 'core',
      'x-ratelimit-used': '36',
      'x-xss-protection': '0'
    },
    data: {
      message: 'Validation Failed',
      errors: [
        {
          resource: 'Release',
          code: 'invalid',
          field: 'target_commitish'
        }
      ],
      documentation_url: 'https://docs.github.com/rest/reference/repos#update-a-release'
    }
  },
  request: {
    method: 'PATCH',
    url: 'https://********/releases/64928231',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'probot/12.2.1 octokit-core.js/3.5.1 Node.js/16.13.0 (linux; x64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"body":"## Changelog\\n* No changes\\n","draft":true,"prerelease":false,"name":"v2.0.101 🌈","tag_name":"v2.0.101","target_commitish":"refs/pull/1023/merge"}',
    request: {}
  },
```
Workflow file
```
jobs:
  build:
    runs-on: linux
    if: ${{ contains(github.event.pull_request.labels.*.name, 'release') }}
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
          token: ******
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: release-drafter/release-drafter@v5
        id: release
        env:
          GITHUB_TOKEN: ****
      - name: Process new_tag 
        id: process_new_tag
        run: |
            echo "new_tag=${{steps.release.outputs.tag_name}}" >> $GITHUB_ENV
 ```

**Comment by jetersen** [comment]
delete the draft.
Please check closed issues before posting :)

**Comment by sumanth-sure** [comment]
hi @jetersen deleted the draft but it was still no use hence reopened the issue

**Comment by jetersen** [comment]
@sumanth-sure whats the on conditions for your github action?

**Comment by sumanth-sure** [comment]
```
on:
  pull_request:
    types: [opened, synchronize, reopened, edited, labeled, unlabeled]
    paths:
      - x_folder/**
```

**Comment by jetersen** [comment]
I am not sure what your trying to achieve with that workflow?

releaseDrafter is not able to generate tags from a pull requests.

You want to do that on push to a branch.

**Comment by sumanth-sure** [comment]
Apologies for the confusion we use the tag received from the release drafter to bump up the version in our project.

- kustomize edit set image `Tag Value From Release Drafter`

- Once We edit the Yaml's inside Project with the latest version then we wish to push the PR To master.

```
name: Bump version
on:
  pull_request:
    types: [opened, synchronize, reopened, edited, labeled, unlabeled]
    paths:
      - x_folder/**

jobs:
  build:
    runs-on: [self-hosted, Linux]
    if: ${{ contains(github.event.pull_request.labels.*.name, 'release') }}
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
          token: ********
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: release-drafter/release-drafter@v5
        id: release
        env:
          GITHUB_TOKEN: *******
      - name: Process new_tag 
        id: process_new_tag
        run: |
            echo "new_tag=${{steps.release.outputs.tag_name}}" >> $GITHUB_ENV
      - name: "Kustomize Build"
        id: kustomize
        if: steps.release.outputs.tag_name != ''
        uses: ./.github/actions/kube-tools
        with:
          kustomize: "3.5.3"
          command: |
            echo "Setting  image version to ${{env.new_tag}}"
            kustomize edit set image x_docker_image-${{env.new_tag}}
            cd -
```
In This process we are getting the above error

**Comment by sumanth-sure** [comment]
@jetersen  any help on this if possible

**Comment by jetersen** [comment]
as I said, release drafter is not able to generate drafts from a pull requests.

You could try and point the commitish to `master`?

```
      - uses: release-drafter/release-drafter@v5
        id: release
        env:
          GITHUB_TOKEN: *******
        with:
          commitish: master
```

**Comment by ducbm051291** [comment]
I met this issue today, any fix yet?

**Comment by phatblat** [comment]
Just started seeing this same error after enabling the autolabeler. Is there a way to limit the action to only updating the draft release on PR merge?

**Comment by ducbm051291** [comment]
@phatblat Have you resolved this issue yet? I tried many configs but still can't make my workflow work 😢

**Comment by dgokcin** [comment]
anyone with a workaround in the last month?

**Comment by cbou** [comment]
I had the same issue and have an easy fix. Maybe it can work for you.

New repository do not have "master" as first branch but "main".
Since I just wanted to test the Github action I copied the yml file from the marketplace: https://github.com/marketplace/actions/release-drafter with "master".

The error could be catched and explained ^^

**Comment by tekumara** [comment]
To reiterate the above, it's failing on the `pull_request` event because the workflow is running in the context of the merge commit. You'll see a log line like which tells you what `commitish` is and it'll look something like this:
```
seek-oss/aec: Fetching parent commits of refs/pull/419/merge
```

To avoid this error, either:
 1. use the `pull_request_target` event instead. [By design](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target) this will run the workflow in the context of the base of the pull request, ie: `refs/heads/main`. Or,
 1. override `commitish` to point at your master/main branch, e.g. in your workflow yaml:
     ```yaml
      - uses: release-drafter/release-drafter@v5
        with:
          commitish: main
     ```
