### ISSUE TITLE
Parameter ''using: node16' is not supported, use 'docker' or 'node12' instead.

### ISSUE THREAD

**Issue by iamjuuyoung** [release-drafter/release-drafter#1128]
When I run it, the following error occurs.
![image](https://user-images.githubusercontent.com/89368804/165025435-1f620d50-43f6-4a55-9d58-40fb39d5f9c6.png)
I use self hosted.  
Lowering the node version to 12 has the same problem.
I don't know what the problem is.
Help me.

main.yml 
```
  update_release_draft:
      runs-on: self-hosted
      steps:
        - uses: release-drafter/release-drafter@v5
          with:
            config-name: release-drafter-config.yml 
```

release-drafter-config.yml 
```
name-template: 'v$NEXT_MINOR_VERSION'
tag-template: 'v$NEXT_MINOR_VERSION'
categories:
  - title: '🚀 Features'
    label: 'enhancement'
  - title: '🐛 Hotfixes'
    label: 'bug'
  - title: 'ETC'
    label: 'documentation'
change-template: '- $TITLE #$NUMBER @$AUTHOR '
template: |
  ## Uncategorized
  $CHANGES
  ### Bump setup.py version must be included here!
```
