### ISSUE TITLE
I ran into bug and couldn't publish it.

### ISSUE THREAD

**Issue by duolabmeng6** [release-drafter/release-drafter#1189]
https://github.com/duolabmeng6/learn_actions/runs/7517547527?check_suite_focus=true

```
  stack: 'AggregateError: \n' +
    "    Error: Data doesn't contain `nodes` field. Make sure the `paginatePath` is set to the field you wish to paginate and that the query includes the `nodes` field.\n" +
    '        at paginate (/home/runner/work/_actions/release-drafter/release-drafter/v5/dist/index.js:141687:11)\n' +
    '        at async findCommitsWithAssociatedPullRequests (/home/runner/work/_actions/release-drafter/release-drafter/v5/dist/index.js:141499:12)\n' +
    '        at async drafter (/home/runner/work/_actions/release-drafter/release-drafter/v5/dist/index.js:141227:7)\n' +
    '        at async Promise.all (index 1)\n' +
    '    at /home/runner/work/_actions/release-drafter/release-drafter/v5/dist/index.js:8639:19',
  type: 'Error'
```

```
name: 版本信息发布

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - master
  # pull_request event is required only for autolabeler
  pull_request:
    # Only following types are handled by the action, but one can default to all as well
    types: [opened, reopened, synchronize]
  # pull_request_target event is required for autolabeler to support PRs from forks
  # pull_request_target:
  #   types: [opened, reopened, synchronize
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write  # for release-drafter/release-drafter to create a github release
      pull-requests: write  # for release-drafter/release-drafter to add label to PR
    runs-on: ubuntu-latest
    steps:
      # (Optional) GitHub Enterprise requires GHE_HOST variable set
      #- name: Set GHE_HOST
      #  run: |
      #    echo "GHE_HOST=${GITHUB_SERVER_URL##https:\/\/}" >> $GITHUB_ENV

      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
        with:
          config-name: my-config.yml
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

```
name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 新功能'
    labels:
      - 'enhancement'
  - title: '🐛 Bug 修复'
    labels:
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## 版本变化

  $CHANGES
```
