### ISSUE TITLE
Group categories under different headings

### ISSUE THREAD

**Issue by tlylt** [release-drafter/release-drafter#1195]
Hello, would like to ask whether the following use case is already supported?

Say I have two main categories:
1. User Facing Changes
2. Other Changes

Under each main category, I would like to define subcategories such as "documentation", and "refactor".

So ideally I would like to have something like:

```
# User Facing Changes

## Documentation
* ISSUE_NUMBER ISSUE_TITLE (#PR_NUMBER)
* ...

## Another Sub Category

# Other Changes

## Refactor
* ISSUE_NUMBER ISSUE_TITLE (#PR_NUMBER)
* ...

## Another Sub Category
```

From the README, I understand I can do something like:
```yaml
categories:
  - title: 'Documentation'
    label: 'Documentation'
  - title: 'Refactor'
    label: 'Refactor'
```
for categories......the question is: how to further specify that e.g. "Documentation" should go under "User Facing Changes"?
