### ISSUE TITLE
apply multiple labels with a single expression in autolabeler 

### ISSUE THREAD

**Issue by rena2damas** [release-drafter/release-drafter#1203]
Currently there is a single way of applying single labels for each expression:

```yaml
autolabeler:
  - label: 'chore'
    files:
      - '*.md'
    branch:
      - '/docs{0,1}\/.+/'
```

Can you you make it so that it accepts a list of labels? Example:

```yaml
autolabeler:
  - label: ['chore', 'docs']
...
```

**Comment by jetersen** [comment]
Not sure why this is desirable as that would most likely put the PR twice because of the current behavior of categorize pull requests that duplicates a PR for each label category.

**Comment by rena2damas** [comment]
I am not sure I got that . The labeler will run once depending on the the event types configured. I usually run it when a PR is open and labels are applied once. Could you explain better what situation are you referring to ?

**Comment by jetersen** [comment]
so if you have a category one with chore and one with docs.

The PR will show up twice in the release draft.

**Comment by rena2damas** [comment]
Ah I get it now thanks . But then if that is the case, that can happen right now as well then: if 2 rules that are met for the same PR (say chore and docs), then the drafter will show up the same PR twice. That's possibly a bug then (unless the documentation addresses this case).

**Comment by jetersen** [comment]
A PR showing multiple categories is documented as the correct behaviour. There is no good way to prevent that.

The best way would be index of category (order, first label match) but alas it is not although. Changing the behaviour would be breaking as some have come to rely on it.

**Comment by rena2damas** [comment]
I guess better use examples for this to filter out what is expected and what is not. Consider a new PR with title:

_this PR contains chore and docs_

---

config 1:

```yaml
categories:
  - title: "Chore Tasks"
    labels: [chore]
  - title: "Documentation"
    labels: [docs]
    
autolabeler:
  - label: chore
     title: ["/chore/"]
  - label: docs
     title: ["/docs/"]
```

__Result drafter__:

##### Chore Tasts
* _this PR contains chore and docs_ (# 1) @username

##### Documentation
* _this PR contains chore and docs_ (# 1) @username

__Question__: even though the PR entry is replicated, they belong to different categories which in that case that is expected behaviour?

---

config 2

```yaml
categories:
    
autolabeler:
  - label: chore
     title: ["/chore/"]
  - label: docs
     title: ["/docs/"]
```

__Result drafter__:

* _this PR contains chore and docs_ (# 1) @username
* _this PR contains chore and docs_ (# 1) @username

__Question__: because there are no label categories, do we still have that PR entry duplicates and is that expected?
