### ISSUE TITLE
How can only the AutoLabeler work?

### ISSUE THREAD

**Issue by dh-Kang** [release-drafter/release-drafter#1216]
```
name: Release Drafter

on:
  workflow_dispatch:
  push:
    branches:
      - release
  pull_request:
    types: [opened, reopened, synchronize]
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  update_release_draft:
... (same with your sample in ReadMe.md)

```

This is head of my workflow file.

As my understandings, update_release_draft will run every  pushes into release, pull requests into any branches.
I think update release draft and auto labeler will run together always.
But I want to run auto labeler only pull request cases.
Is there any missing in my workflow files?

**Comment by jetersen** [comment]
via action input, sadly they are undocumented but also being removed in v6 as I am going to make autolabeler a separate action.

`disable-releaser` and `disable-autolabeler` can be set to `true`

Like so

```yaml
on:
  pull_request:
    types: [opened, reopened, synchronize]
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  autolabeler:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          disable-releaser: true
```
