### ISSUE TITLE
passing in version wont override version

### ISSUE THREAD

**Issue by TomsOverBaghdad** [release-drafter/release-drafter#1217]
I pass in a version but it doesn't override the $RESOLVED_VERSION. I looked through the code and there's [a line](https://github.com/release-drafter/release-drafter/blob/master/lib/versions.js#L123) where the INPUT_VERSION overrides RESOLVED_VERSION, but I can't figure out how it doesn't end up getting used for the tag and name.

Github logs showing that the correct version is passed through

<img width="383" alt="Screen Shot 2022-09-02 at 4 38 16 PM" src="https://user-images.githubusercontent.com/6117043/188232155-8b2a2450-4890-48b9-b2a1-2e4d880d4fc1.png">

Logs showing that the generated values are incorrect

<img width="512" alt="Screen Shot 2022-09-02 at 4 38 31 PM" src="https://user-images.githubusercontent.com/6117043/188232154-d7433228-a69b-4694-8f01-d1d74b8ff9d7.png">

github action:
```yaml
 - name: Draft release
    id: draft_release
    uses: release-drafter/release-drafter@v5
    with:
      config-name: ${{ inputs.drafter_config }}
      version: ${{ steps.determine_version.outputs.version }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

config file:

```yaml
name-template: '$RESOLVED_VERSION 🌈'
tag-template: '$RESOLVED_VERSION'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
template: |
  ## What’s Changed

  $CHANGES
```
