### ISSUE TITLE
$NUMBER is missing from release

### ISSUE THREAD

**Issue by jonny7** [release-drafter/release-drafter#1223]
Hi

I've suddenly started getting missing PR numbers from the draft.

Changes

    Feature/very special @jonny7 ()

🚀 Features

    Release Candidate with new features @jonny7 ()

🧰 Maintenance

    Release Candidate with new features @jonny7 ()

This is my release-draft

```yml
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
prerelease: true
autolabeler:
  - label: 'chore'
    files:
      - '*.md'
    branch:
      - '/docs{0,1}\/.+/'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
    body:
      - '/JIRA-[0-9]{1,4}/'
template: |
  ## Changes

  $CHANGES
```

And I'm running it on these events
```yml
on:
  pull_request:
    types:
      - closed
    branches:
      - 'release/**'
```      

```yml
      - uses: release-drafter/release-drafter@v5
        with:
          disable-autolabeler: true
          config-name: release-drafter.yml
          commitish: main
          publish: true
          version: 1.0.0
          name: 1.0.0
          tag: 1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
It was working fine, but I'm not sure the cause of it stopping.
