### ISSUE TITLE
Is it possible to write draft release version in a repo file?

### ISSUE THREAD

**Issue by fabn** [release-drafter/release-drafter#1234]
I'm moving to release drafter and in my old workflow I were used to write the current app version in a file stored in the repo (named `VERSION`).

Is it possible to have release drafter to write and commit this file as well, when drafting release?

I'm relatively new with GH workflows so maybe is something simple to achieve but I'm not able to figure out how.

**Comment by jetersen** [comment]
You can combine actions.

We do have step output: https://github.com/release-drafter/release-drafter#action-outputs

So you can design anything.

See my example here:
https://github.com/release-drafter/release-drafter/blob/df69d584deac33d8569990cb6413f82447181076/.github/workflows/release.yml#L45-L60

**Comment by fabn** [comment]
I solved with this, so I'll leave here for future readers

```yaml
    steps:
      - uses: release-drafter/release-drafter@v5
        id: release-drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Bump version file and commit the result
      - uses: actions/checkout@v2
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      - name: Write version file
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: |
          echo -n "${{ steps.release-drafter.outputs.tag_name }}" > VERSION

      # Commit change to VERSION file if changed, it won't trigger a new workflow run
      # See https://github.com/marketplace/actions/add-commit#the-commit-from-the-action-is-not-triggering-ci
      - name: Bump version file
        uses: EndBug/add-and-commit@v9
        with:
          add: 'VERSION'
          message: 'Bump VERSION file'
```
