### ISSUE TITLE
I would like to see skip added to the default of version-resolver.

### ISSUE THREAD

**Issue by akira-toriyama** [release-drafter/release-drafter#1236]
Thank you for the wonderful `Action`👨‍💻

I would like to see no release drafts made except for `break`, `feat` and `fix`.

```yml
# .github/release-drafter.yml
version-resolver:
  major:
    labels:
      - 'break'
  minor:
    labels:
      - 'feat'
  patch:
    labels:
      - 'fix'
  # Add skip or null    
  default: skip
```

**Comment by jetersen** [comment]
What's wrong with naturally having patch as the default?

When would a PR not update version. Is it because your automatically releasing on every PR?

If so make a action that skips if no label exist?

**Comment by akira-toriyama** [comment]
@jetersen Thanks for the reply.

> When would a PR not update version. 

`label` is `skip`

```yml
# .github/release-drafter.yml
version-resolver:
  major:
    labels:
      - 'break'
  minor:
    labels:
      - 'feat'
  patch:
    labels:
      - 'fix'
  
  skip: # skip or not_release
    labels:
      - 'skip'
      - 'not_release'
```

----

> If so make a action that skips if no label exist?

Thanks for the idea.
I tried, but it didn't work.

```yml
# .github/workflows/release-drafter.yml
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  update_release_draft:

    if: github.event.label.name != 'skip' # <- Added condition. 👨‍💻
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
```
