### ISSUE TITLE
tag version override on name input

### ISSUE THREAD

**Issue by jiyeonseo** [release-drafter/release-drafter#1248]
`RESOLVED_VERSION` has been overridden as name input after I configured the action as below.

```yaml
# .github/workflows/release-drafter.yml
 steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y.%m.%d')"
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
        with:
          name : ${{ steps.date.outputs.date }} 🚂
        #   config-name: my-config.yml
        #   disable-autolabeler: true
       env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
```

```yaml
# .github/release-drafter.yml
name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
```

What I wanted was a release name like '2022-10-16' and just the same versioning style. (eg. `v0.1.0`). but the version changed to `v2022-10-16` 

I found [this code](https://github.com/release-drafter/release-drafter/blob/master/lib/releases.js#L348) when the new version is created, it uses a version, tag, and name as well. I think `name` shouldn't be used here as it's for the name of the release, not the version. (https://github.com/release-drafter/release-drafter#action-inputs) If I'm wrong, plz let me know! 

Is this intended? Or is it a bug?
