### ISSUE TITLE
Exclude PRs which doesn't have any label on $CHANGES

### ISSUE THREAD

**Issue by anoop0567** [release-drafter/release-drafter#1253]
Hi, how can we exclude the PRs which doesn't have any label on $CHANGES or can we add a default label on autolabeller if no condition matches like `skip-changelog`

Current release-drafter.yml autolabeler

```
autolabeler:
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
      - '/enhancement\/.+/'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
      - '/bug\/.+/'
  - label: 'chore'
    branch: '/chore\/.+/'
```

Expected release-drafter.yml autolabeler
```
autolabeler:
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
      - '/enhancement\/.+/'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
      - '/bug\/.+/'
  - label: 'chore'
    branch: '/chore\/.+/'
  - defaultLabel: 'skip-changelog'
```
