### ISSUE TITLE
Not detecting last release properly

### ISSUE THREAD

**Issue by didix21** [release-drafter/release-drafter#1263]
I'm facing the following issue, release-drafter is launch and he detects there is v5.22.0 draft. For some reason is detecting as the latest release v5.20.0 but v5.21.0 exists. Check the following image:

<img width="290" alt="image" src="https://user-images.githubusercontent.com/12051781/200510410-461e86ef-74da-4dc1-9590-3cf9d09c8b05.png">

Logs provided by release drafter:
```
Run release-drafter/release-drafter@v5
"pull_request_target.opened" is not a known webhook name (https://developer.github.com/v3/activity/events/types/)
"pull_request_target.reopened" is not a known webhook name (https://developer.github.com/v3/activity/events/types/)
"pull_request_target.synchronize" is not a known webhook name (https://developer.github.com/v3/activity/events/types/)
"pull_request_target.edited" is not a known webhook name (https://developer.github.com/v3/activity/events/types/)
didix21/my-release-draft-test: Found 34 releases
{ name: 'event', id: '3417496876' }
didix21/my-release-draft-test: Draft release: v5.22.0
{ name: 'event', id: '3417496876' }
didix21/my-release-draft-test: Last release: v5.20.0
{ name: 'event', id: '3417496876' }
didix21/my-release-draft-test: Fetching parent commits of main since 2022-11-07T16:01:58Z
{ name: 'event', id: '3417496876' }
didix21/my-release-draft-test: Updating existing release
{ name: 'event', id: '3417496876' }
```

Moreover, if I call:
```
gh api \                                                                                                                   ✔  5s 
  -H "Accept: application/vnd.github+json" \
  /repos/$OWNER/$REPO/releases/latest
```
The returned version is v5.21.0 not v5.20.0.

Here you'll see my release-draft workflow:
```
name: Release Drafter

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  update_release_draft:
    if: ${{ github.event.pull_request.merged  ||  github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref_name == 'main') }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Check github variables'
        run: |
          echo "Github is merged: ${{ github.event.pull_request.merged }}"
          echo "Event name: ${{github.event_name }} "
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-main.yml # located in .github/ in default branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Here the template:
```
name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
filter-by-commitish: true
commitish: main
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 
      - 'chore'
      - 'maintenance'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
prerelease: true
version-resolver:
  major:
    labels:
      - 'breakingchange'
  minor:
    labels:
      - 'enhancement'
  patch:
    labels:
      - 'bug'
  default: minor 
template: |
  ## Changes
  $CHANGES
```

Any help will be apreciated, thanks.
