### ISSUE TITLE
Release Drafter incorrectly detects Release (thinks v5.0.0, but at v12.0.0)

### ISSUE THREAD

**Issue by TTvanWillegen** [release-drafter/release-drafter#1277]
We've been using Release Drafter for some years now. However, it consistently detects the incorrect version.
It drafted a release once correctly, v5.0.0, but then remained to draft new v5.0.0 versions including the old PRs.

I've manually removed the old PRs from the release before releasing, but it gets rather annoying to do, as you can guess.
The following releases (+tags) exist in our repository.
```text
v12.0.0
v11.0.0
v10.2.0
v10.1.0
v9.0.0
v8.0.0
v7.0.0
v5.0.0 (⇽ the one originally drafted by this repo)
older ones, pre-"release-drafter-era"
```
The person releasing all these releases according to github is `github-actions`, not me.
![image](https://user-images.githubusercontent.com/15815200/205595106-0d1b5237-9ffa-4cda-9dff-d784ec5ac017.png)
![image](https://user-images.githubusercontent.com/15815200/205595140-759d5649-7249-4808-b256-811f65820f32.png)

Removing the draft and pushing a new commit / PR to the dev branch generates the same draft release.

**.github > workflows > release-drafter.yml**
```
name: Automatic Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - dev

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "dev"
      - uses: release-drafter/release-drafter@v5
        with:
#         (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
**.github > release-drafter.yml**
```
name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'Feature'
  - title: '📈 Improvements'
    labels:
      - 'Improvement'
      - 'Styling'
  - title: '🕷 Bug Fixes'
    labels:
      - 'Bug'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
version-resolver:
  major:
    labels:
      - 'Feature'
  minor:
    labels:
      - 'Improvement'
      - 'Styling'
  patch:
    labels:
      - 'Bug'
      - 'Chore'
  default: patch
include-labels:
  - 'Feature'
  - 'Improvement'
  - 'Styling'
  - 'Bug'
  - 'Chore'
exclude-labels:
  - 'Exclude CL'
template: |
  ## What's Changed
  $CHANGES
```
