### ISSUE TITLE
Reusable workflow

### ISSUE THREAD

**Issue by piotrooo** [release-drafter/release-drafter#1278]
Hello!
Thanks for a great lib!

I want to ask is release-drafter support a reusable workflows?
Let's say I have organization `acme`. In this organization I have an internal repository (this org is part of enterprise account) `github-workflows`.

File `github-workflows/.github/workflows/acme-release-drafter.yml` contains release-drafter configuration:

```yaml
name: Fancy Release Drafter

on:
  workflow_call:

permissions:
  contents: read

jobs:
  update-release-log:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5.21.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

In the `acme/sample` repository I want to use this workflow.

File `sample/.github/workflows/drafter.yml` contains:

```yaml
name: Drafter

on:
  push:
    branches: [ main ]
  
jobs:
  ci: 
    uses: acme/github-workflows/.github/workflows/acme-release-drafter.yml@main
```

`release-drafter` configuration file is in a `acme/github-workflows` repository and should be shared through all organization repos.

This configuration results this warning:

```
Warning: acme/sample: Invalid config file
{
  name: 'event',
  id: '362[13](https://github.com/acme/sample/actions/runs/3642328050/jobs/7329097273#step:2:14)58050',
  stack: 'Error: Configuration file .github/release-drafter.yml is not found. The configuration file must reside in your default branch.\n' +
    '    at getConfig (/home/runner/work/_actions/release-drafter/release-drafter/v5.21.1/dist/index.js:[14](https://github.com/acme/sample/actions/runs/3642328050/jobs/7329097273#step:2:15)2717:13)\n' +
    '    at async drafter (/home/runner/work/_actions/release-drafter/release-drafter/v5.21.1/dist/index.js:142347:20)\n' +
    '    at async Promise.all (index 0)',
  type: 'Error'
}
Error: Invalid config file
```

**Comment by jetersen** [comment]
You still need a config files.

Optionally you can make a default config file at `acme/.github` repo under the path `.github/release-drafter.yml`
See: https://github.com/specshell/.github/blob/main/.github/release-drafter.yml

**Comment by jetersen** [comment]
`.github` is meant to be public for many other reasons it is a special repo.

If you want a privat config (Not sure I see the need here) you need to use `_extends` and config inside each repo.
Potentially you need to provide a custom github token with the correct read permissions.

**Comment by jetersen** [comment]
It will if you provide a custom GitHub Token with the right permission.

I would advise against it at your setup will be more complex and requires a config file in each repo.

With the .github repo you only need the workflow cause the action will automatically pick up the config in the .github repo

**Comment by piotrooo** [comment]
Ok I give small recap how I currently did it.

### acme/github-workflows 
Repository with shared workflows through whole organization.
Visibility: `internal`

* `github-workflows/.github/workflows/acme-release-drafter.yml` with Release Drafter workflow:

```yaml
name: Acme Release Drafter

on:
  workflow_call:

permissions:
  contents: read

jobs:
  update-release-log:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5.21.1
        env:
          # RELEASE_DRAFTER is an action secret with organization scope.
          # Contains PAT with scope repo.
          GITHUB_TOKEN: ${{ secrets.RELEASE_DRAFTER }}

```

* `github-workflows/.github/release-drafter.yml` Release Drafter configuration (template, categories mapping, exclude-labels and so on)

---

### acme/sample
Repository which reuse workflow defined in the `acme/github-workflows` repository.
Visibility: `internal`

* `sample/.github/workflows/drafter.yml` action which triggers Release Drafter

```yaml
name: Release Drafter

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  update-release-log:
    permissions:
      contents: write
    uses: acme/github-workflows/.github/workflows/acme-release-drafter.yml@main
    secrets: inherit
```

* `sample/.github/release-drafter.yml` configuration for Release Drafter which use for [_extends](https://github.com/probot/octokit-plugin-config#the-_extends-key) Probot feature.

```yaml
_extends: github-workflows
```

Repositories configured in that way allows me to run a Release Drafter for internal repositories in the organization.

---

I've also try to use a **Fine-grained personal access tokens** for organizations but it seems to not work correctly with a GraphQL.

```
HttpError: Personal access tokens with fine grained access do not support the GraphQL API
```

It seems to be a GitHub issue https://github.com/cli/cli/issues/6680.
