### ISSUE TITLE
Error: Data doesn't contain `nodes` field. Make sure the `paginatePath` is set to the field you wish to paginate and that the query includes the `nodes` field.

### ISSUE THREAD

**Issue by hubertklusek** [release-drafter/release-drafter#1290]
release-drafter configuration:

      - name: Publish release MINOR
        if: ${{ (github.ref == 'refs/heads/main') }}
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yaml
          publish: true
          name: "$NEXT_MINOR_VERSION"
          tag: "$NEXT_MINOR_VERSION"
          version: "$NEXT_MINOR_VERSION"
          commitish: "${{ github.sha }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish release PATCH
        if: ${{ startsWith(github.ref,'refs/heads/support-') }}
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yaml
          publish: true
          name: "$NEXT_PATCH_VERSION"
          tag: "$NEXT_PATCH_VERSION"
          version: "$NEXT_PATCH_VERSION"
          commitish: $NEXT_PATCH_VERSION"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

Error log:

Run release-drafter/release-drafter@v5

...

Error: Error: Data doesn't contain `nodes` field. Make sure the `paginatePath` is set to the field you wish to paginate and that the query includes the `nodes` field.
        at paginate (/home/runner/work/_actions/release-drafter/release-drafter/v5/dist/index.js:142848:11)
        at async findCommitsWithAssociatedPullRequests (/home/runner/work/_actions/release-drafter/release-drafter/v5/dist/index.js:142646:12)
        at async drafter (/home/runner/work/_actions/release-drafter/release-drafter/v5/dist/index.js:142388:7)
        at async Promise.all (index 0)

**Comment by Googlom** [comment]
in my case, the issue was with input `commitish`. I copied the workflow from a repository where it was pointing to `master`, but I needed `main` instead.

**Comment by cchanche** [comment]
Hi @hubertklusek , this has bee quite some time. I hope you ended up finding a solution.

For reference, reading your inputs, I think @Googlom is correct. Your `commitish:` values look wrong to me.

They should basically contain a branch name, which is inside the github.ref or github.ref_name variable (in any action).

I see you have a release setup for some patches. Here is my implementation of a workflow that does something similar : 

```yaml
      - name: Release drafter
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.hotfix.yaml
          disable-autolabeler: true
          commitish: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
