### ISSUE TITLE
why would release-drafter update the wrong release version?

### ISSUE THREAD

**Issue by jeacott1** [release-drafter/release-drafter#1307]
Hi all,
 I'm testing release-drafter but am having an odd issue.

I have an existing release draft created by release drafter  -> Draft release: v0.2.9, sha=d67b2
I add a new tag v0.2.10 at a newer commit=2b383cde (commit already exists) and invoke release-drafter via tag push and a github trigger on: create:
both commits are on main.

release-drafter seems to have all the info, but chooses to update the original release (v0.2.9) instead of creating a new one at the new commit sha. the updated release maintains its old sha too.  why doesnt release-drafter choose to create a new release at the provided tag?

```
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create Release
        uses: release-drafter/release-drafter@v5
        with:
          version: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          commitish: main
          publish: false
```

```
Run release-drafter/release-drafter@v5
  with:
    version: v0.2.10
    name: Release v0.2.10
    commitish: main
    publish: false
    config-name: release-drafter.yml
  env:
    CI_REPOSITORY_SLUG: mytestworld-workflow-test
    CI_REPOSITORY_OWNER: mytestworld
    CI_REPOSITORY_OWNER_SLUG: mytestworld
    CI_REPOSITORY_NAME: workflow-test
    CI_REPOSITORY_NAME_SLUG: workflow-test
    CI_REPOSITORY: mytestworld/workflow-test
    CI_REF_SLUG: refs-tags-v0-2-10
    CI_REF_NAME: v0.2.10
    CI_REF_NAME_SLUG: v0-2-10
    CI_REF: refs/tags/v0.2.10
    CI_ACTION_REF_NAME: v0.2.10
    CI_ACTION_REF_NAME_SLUG: v0-2-10
    CI_HEAD_REF: 
    CI_BASE_REF: 
    CI_SHA_SHORT: 2b383cde
    CI_SHA: 2b383cde3c7d1fb723821ccb2fc09e80cf3620d1
    CI_ACTOR: me
    CI_EVENT_NAME: create
    CI_RUN_ID: 4022873253
    CI_RUN_NUMBER: 25
    CI_WORKFLOW: create new release
    CI_ACTION: env-vars
    GITHUB_TOKEN: ***
"pull_request_target.opened" is not a known webhook name (https://developer.github.com/v3/activity/events/types/)
"pull_request_target.reopened" is not a known webhook name (https://developer.github.com/v3/activity/events/types/)
"pull_request_target.synchronize" is not a known webhook name (https://developer.github.com/v3/activity/events/types/)
"pull_request_target.edited" is not a known webhook name (https://developer.github.com/v3/activity/events/types/)
mytestworld/workflow-test: Found 9 releases
{ name: 'event', id: '4022873253' }
mytestworld/workflow-test: Draft release: v0.2.9
{ name: 'event', id: '4022873253' }
mytestworld/workflow-test: No last release found
{ name: 'event', id: '4022873253' }
mytestworld/workflow-test: Fetching parent commits of main
{ name: 'event', id: '4022873253' }
mytestworld/workflow-test: Updating existing release
{ name: 'event', id: '4022873253' }
```

hope someone has some insight. is it because release-drafter can't cope with on: create: ?
thanks
