### ISSUE TITLE
Error: Invalid config file when trying to fetch the config file from a private <ORGANIZATION>/.github repository (special repository)

### ISSUE THREAD

**Issue by AllanOricil** [release-drafter/release-drafter#1328]
I'm using `release-drafter@v5.23.0`

This is where I've placed my `release-drafter.yml` config file in the `<ORGANIZATION>/.github` special repository

````shell
<ORGANIZATION>/.github
└── .github
    ├── workflows
    └── release-drafter.yml
````

This is my reusable workflow, which is at `<ORGANIZATION>/github-reusable-workflows`

````yml
name: Release Drafter Workflow

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: false

permissions:
  contents: write
  pull-requests: write

jobs:
  release-drafter:
    runs-on: ubuntu-latest

    steps:
      - uses: release-drafter/release-drafter@v5.23.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }}
        with:
          commitish: main
````

This is my caller workflow, which is called from `<ORGANIZATION>/my-repo`. I'm passing a custom Github PAT that grants access to any private repository that is within the same Organization

````yml
name: Release Drafter Workflow

on:
  push:
    branches:
      - main

  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  release-drafter:
    uses: <ORGANIZATION>/github-reusable-workflows/.github/workflows/release-drafter.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
````
This is the `release-drafter.yml` config file that I added to `<ORGANIZATION>/my-repo/.github`:

````yml
_extends: .github
````

I also tried this one:

````yml
_extends: .github:.github/release-drafter.yml
````

None of them worked. I'm always getting the same output shown below

![image](https://user-images.githubusercontent.com/55927613/223771067-79eb014e-703a-4cbc-8447-3c60e6b7aa59.png)
![image](https://user-images.githubusercontent.com/55927613/223771160-9fcd8061-e7ec-457c-9422-fc33db2e3b09.png)
![image](https://user-images.githubusercontent.com/55927613/223771214-19553b68-37fd-4f89-b04d-45c058a22c12.png)
![image](https://user-images.githubusercontent.com/55927613/223771258-21ac5ab0-8653-447e-a647-6afacd53888f.png)
