### ISSUE TITLE
Support custom PR $body Markdown selector

### ISSUE THREAD

**Issue by kuhnroyal** [release-drafter/release-drafter#1329]
Currently the full PR body is made available via the `$body` variable.
A lot of PR bodies are way to big to be useful for a changelog.

It would be great if there was a way to provide a selector for a sub-part of the PR body.
Something like:

```yaml
pr-body-selector:
  selector: '## Release information'
  not-found: 'empty/full'
```
