### ISSUE TITLE
question: how to use github context in config file?

### ISSUE THREAD

**Issue by h3n4l** [release-drafter/release-drafter#1345]
Hi, release-drafter team, I'm using release-drafter to create a release drafter when the **tag push event** fires.

But when I try to use the github context in the config file, it doesn't seem to work.

Here is the action file I use:

```yml
name: Build Release Artifacts and Draft Release

on:
  push:
    tags:
      - "*.*.*"

permissions:
  contents: read

draft-release:
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        name: Draft Release
        id: create-draft-release
        with:
          config-name: workflows-config/release-drafter.yml
          disable-autolabeler: true
          tag: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Config file:
```yml
name-template: ${{ github.ref_name }} 🌈
template: |
  ## Changes
  $CHANGES
```

And IMO, the release name should be like `0.0.1 🌈`, but I get the following:
<img width="609" alt="CleanShot 2023-06-07 at 22 43 32@2x" src="https://github.com/release-drafter/release-drafter/assets/87714218/6fa58421-da4d-499e-a201-ee55d2c8c721">

Did I miss something?

**Comment by ahenriksen-esri** [comment]
@h3n4l - One option you can try is to use environment variables to set the `name` config value in the `.gitbub/workflow/release-drafter.yml` file instead of in the template. We use date-based versioning for our project, so I did this:

```YAML
name: 'Release Drafter'
run-name: 'Release Drafter'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, reopened, synchronize ]

permissions:
  contents: read

jobs:
  update_release_draft:
    runs-on: [ ubuntu-latest ]
    name: Update Release Draft
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Set Environment Variables
        run: |
          echo "RELEASE_NAME=[Draft] Next Release" >> $GITHUB_ENV
          echo "RELEASE_TAG=v$(date +'%Y').$(date +'%m').$(date +'%d')" >> $GITHUB_ENV
          echo "RELEASE_VERSION=v$(date +'%Y').$(date +'%m').$(date +'%d')" >> $GITHUB_ENV

      - name: Draft Release
        uses: release-drafter/release-drafter@v5.21.1
        with:
          commitish: main
          name: ${{ env.RELEASE_NAME }}
          tag: ${{ env.RELEASE_TAG }}
          version: ${{ env.RELEASE_VERSION }}
          publish: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by cchanche** [comment]
Config file does not expand github actions expressions.

However, for your scenario, you can just do this : 

```yaml
      - uses: release-drafter/release-drafter@v5
        name: Draft Release
        with:
          config-name: workflows-config/release-drafter.yml
          disable-autolabeler: true
          tag: ${{ github.ref_name }}
          name: ${{ github.ref_name }} # add this, overrides config's 'name-template'
```
