### ISSUE TITLE
Resource not accessible by integration for the default token, the action is green nevertheless

### ISSUE THREAD

**Issue by oleg-nenashev** [release-drafter/release-drafter#1350]
I hit a weird behavior in https://github.com/wiremock/wiremock-testcontainers-go that has lasted since a few days ago

- The action uses the default GitHub token and `@v5` of the action, similarly to all other repositories where the action runs successfully: https://github.com/wiremock/wiremock-testcontainers-go/blob/main/.github/workflows/changelog-draft.yml
- The workflow runs are green and and the Release drafter step is green too
- But... there is no release draft
- When you open the GitHub action , there is an annotation with the execution failure that actually should not happen for the default token

Any ideas about what's wrong with this repo would be appreciated. I also suggest failing the action by default in the case of such errors.

## Action view

![image](https://github.com/release-drafter/release-drafter/assets/3000480/d60924f6-2b9d-4fb4-8a37-7037061fdc47)

## Execution log

![image](https://github.com/release-drafter/release-drafter/assets/3000480/06d7ac26-9a09-46e1-a421-4cbffe20bc45)

**Comment by jetersen** [comment]
I believe you need to add the permission block on any new workflows which is due to GitHub recent increased security to GitHub Actions.

```yaml
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
```

**Comment by oleg-nenashev** [comment]
> I believe you need to add the permission block to the steps section on any new workflows which is due to GitHub recent increased security to GitHub Actions.

The thing is that it was an old workflow that actually worked before... and works now. So ther ewas a temporary glitch somewhere.

@jetersen what do you think about failing the action by default if a request fails?

**Comment by oleg-nenashev** [comment]
Nevertheless, I confirm it fixes the issue itself

**Comment by arnaugm** [comment]
I have a similar issue when not providing the token, the action is green but when you inspect the RD step then you see the error there, would help if these errors fail the action.

**Comment by aobort** [comment]
Hi,
The same issue appeared when I create PRs **from fork** to upstream repo. When pushing to a feature branch in target repo and create PR from it, then all good. The workflow file is like this:

```yaml
name: Release Drafter

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          disable-releaser: github.ref != 'refs/heads/main'
          config-name: release-drafter.yml
          commitish: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
which results to green check, but errors inside:
```
Error: Resource not accessible by integration
{
  name: 'HttpError',
  id: '8621[25](https://github.com/***/actions/runs/8621254699/job/23629713494?pr=127#step:2:26)4699',
  status: 403,
  response: {
    url: 'https://api.github.com/repos/***/issues/1[27](https://github.com/***/actions/runs/8621254699/job/23629713494?pr=127#step:2:28)/labels',
    status: 403,
```
