### ISSUE TITLE
Allow `replacers` to uppercase/lowercase capturing groups

### ISSUE THREAD

**Issue by stinodego** [release-drafter/release-drafter#1363]
My contributors do not always format their pull request titles appropriately, so I want to implement a replacer that always uppercases the first letter of the changelog entry. I tried this:

```yaml
replacers:
  # Uppercase the first letter of each changelog entry
  - search: '/- ([a-z])/g'
    replace: '- \u$1'
```

The `\u` works for some regex replacers, like in VSCode. However, this does not seem to work. Is there a way I can achieve this? If not, consider this a feature request!

**Comment by jetersen** [comment]
JavaScript sees the \u as an Unicode rather than a regex replacement.

I can't find any NPM package that implements this behavior so either we have written something or simply accept this is not something that is supported in JavaScript 😅

**Comment by cchanche** [comment]
I think this should be part of your PR title linting strategy - not release-drafter changelog output mechanism.

If you prefer uppercased PR title, I guess that also applies to ongoing (open) pull-requests - not the changelog entry alone.

```yaml
name: PR Title Check
on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title is capitalized
        uses: actions/github-script@v6
        with:
          script: |
            const prTitle = context.payload.pull_request.title;
            if (!/^[A-Z]/.test(prTitle)) {
              core.setFailed("❌ PR title must start with a capital letter.");
            } else {
              console.log("✅ PR title is properly capitalized.");
            }
```

feel free to reopen (or ask for it) if this is still relevant
