### ISSUE TITLE
Feature: Add the ability to set the default category

### ISSUE THREAD

**Issue by andrey-helldar** [release-drafter/release-drafter#1374]
In order for a PR to be included in a category, it must be assigned a label.

In this case, the categories are displayed in the order in which they are defined in the configuration file.

But those PRs that do not fall into any of the categories will always be displayed above them. Thus, we will get something like this:

```markdown
## Changed

- Something 1
- Something 2

## Added

- Something 3

## Fixed

- Something 4

## Removed

- Something 5
```
Let's say I want to change the location of a PR without labels between "Added" and "Fixed".

Now for this I need to add tags to all such PRs. But what if there are a lot of these PRs? This will become a tedious task.

Therefore, I propose to consider adding a new attribute for categories - `default`.

Thanks to it, we will be able to determine the order in which records are displayed ourselves. For example, like this:

```yaml
categories:
  - title: 'Added'
    labels:
      - 'added'

  - title: 'Changed'
    default: true

  - title: 'Fixed'
    labels:
      - 'fix'
      - 'bug'

  - title: 'Removed'
    labels:
      - 'removed'

template: $CHANGES
```

```markdown
## Added

- Something 3

## Changed

- Something 1
- Something 2

## Fixed

- Something 4
```
