### ISSUE TITLE
Why does setting latest to false in yml still result in release marked as "latest"?

### ISSUE THREAD

**Issue by mellis481** [release-drafter/release-drafter#1375]
The title says it all.

My `.release-drafter.yml` file is defined below.
```
name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
latest: 'false'
categories:
    - title: '🚀 Features'
      labels:
          - 'feature'
          - 'enhancement'
    - title: '🐛 Bug Fixes'
      labels:
          - 'fix'
          - 'bugfix'
          - 'bug'
    - title: '🧰 Maintenance'
      label: 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
    major:
        labels:
            - 'major'
    minor:
        labels:
            - 'minor'
    patch:
        labels:
            - 'patch'
    default: patch
template: |
    ## Changes

    $CHANGES
```

I've tried `latest: 'false'` (as a string) and `latest: false` (as a boolean), but it still results in my release being marked "latest". What am I doing wrong?
