### ISSUE TITLE
Version resolver has issues with first major release

### ISSUE THREAD

**Issue by bheemvennapureddy** [release-drafter/release-drafter#1391]
I have tagged my pr with major label but still my release created was a minor version 

attached logs 
[logs_23635967043.zip](https://github.com/release-drafter/release-drafter/files/15270041/logs_23635967043.zip)

**Comment by bheemvennapureddy** [comment]
```
config used : 

---
name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
prerelease: true
include-pre-releases: true

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'infrastructure'
      - 'automation'
      - 'documentation'
      - 'dependencies'
      - 'ci'
      - 'test'
      - 'codecov'
      - 'testing'
      - 'refactor'
      - 'unit tests'
      - 'release'
  - title: '🏎 Performance'
    labels: 
      - 'performance'
      - 'load'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
autolabeler:
  - label: 'documentation'
    branch:
      - '/docs{0,1}\/.+/'
      - '/documentation\/.+/'
    files:
      - 'README.md'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
      - '/bug\/.+/'
      - '^fix.*'
    title:
      - '/fix/i'
      - '/bug/i'
      - '^fix.*'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
  - label: 'maintenance'
    branch:
      - '/maintenance\/.+/'
  - label: 'dependencies'
    branch:
      - '/dependencies\/.+/'
```
