### ISSUE TITLE
Access tag-template in template?

### ISSUE THREAD

**Issue by amaury-hanser** [release-drafter/release-drafter#1394]
Hello, 

Thanks for the awesome work, it speeds up a lot our release process.

I have a question regarding the creation a of link to the full changelog.
I have a monorepo and I have different release-drafter files in order to have different configuration, they all extend the same `base.yml` file.

In the template I have added a link to the changelog:
```  
For the detail-oriented, here's the full list of changes: [Full Changelog between $PREVIOUS_TAG and $RESOLVED_VERSION](https://github.com/organization/repo/compare/$PREVIOUS_TAG...$RESOLVED_VERSION)
``` 

### Issue

`$RESOLVED_VERSION` doesn't contain the `template-tag` and the link is therefore incorrect:

#### Current behavior:

`https://github.com/organization/repo/compare/foobar_v1.9.1...v1.9.2` 

#### Expected behavior: 

`https://github.com/organization/repo/compare/foobar_v1.9.1...foobar_v1.9.2` 

### Configuration

⚠️ Please note that everything above `name-template` is in a separate files `base.yml` and is extended in `foobar.yml` but for the sake of brevity I've put everything in a single block of code.

```
commitish: main
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'docs'
change-template: '- $TITLE by @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## What's new
  [...]

  ## Full Changelog

  For the detail-oriented, here's the full list of changes: [Full Changelog between $PREVIOUS_TAG and $RESOLVED_VERSION](https://github.com/organization/repo/compare/$PREVIOUS_TAG...$RESOLVED_VERSION)

name-template: "foobar_v$RESOLVED_VERSION"
tag-template: "foobar_v$RESOLVED_VERSION"
tag-prefix: foobar_v
include-paths:
  - apps/foobar/
  ```

Any help would be appreciated

**Comment by amaury-hanser** [comment]
I've asked about `tag-template`, but being able to use `tag-prefix` would also work just fine.

**Comment by cchanche** [comment]
Oh I see, that's a nice catch @amaury-hanser, thank you !

This has been a long time, sorry for that, but I think this deserves a fix.

I like to think `$[*]_VERSION` variable should remain versions (numeric, semver), instead of tags.

As a quick fix, your local config could overwrite the footer (only) with the correct prefix like :

```yaml
_extends: some-repo:the_base_config.yml
name-template: "foobar_v$RESOLVED_VERSION"
tag-template: "foobar_v$RESOLVED_VERSION"
tag-prefix: foobar_v
include-paths:
  - apps/foobar/
footer: |
  For the detail-oriented, here's the full list of changes: [Full Changelog between $PREVIOUS_TAG and $RESOLVED_VERSION](https://github.com/organization/repo/compare/$PREVIOUS_TAG...foobar_v$RESOLVED_VERSION)
```

You would have to rewrite the base config to use a footer aswell.

For long-term solution, I believe we should add new variables that are similar to $RESOLVED_VERSION, $NEXT_MAJOR_VERSION, etc..., but with the tag prefix included (whether it was specified as an actual `tag-prefix:` or not).

For instance: `$RESOLVED_TAG` maybe ?

I'll see when I have time to work on this. Contributions are welcome
