### ISSUE TITLE
Exclude labels from categorisation

### ISSUE THREAD

**Issue by JakobHavtorn** [release-drafter/release-drafter#1398]
When [categorising pull requests](https://github.com/release-drafter/release-drafter?tab=readme-ov-file#categorize-pull-requests), is it possible to also define a set of labels to exclude from a category?

Our use-case is Dependabot has its PRs labelled with `dependencies` but also one of `major`, `minor`, or `patch` (usually `minor` or `patch`). We would like to collect all PRs labelled `dependabot` in one category while not including them in the other categories.

The syntax would look something like the below.

```yaml
categories:
  - title: '🔴 Major changes'
    label: 'major'
    exclude-label: `dependabot`
  - title: '🟠 Minor changes'
    label: 'minor'
    exclude-label: `dependabot`
  - title: '🟡 Patch changes'
    label: 'patch'
    exclude-label: `dependabot`
  - title: '📦 Dependencies'
    collapse-after: 0
    label: dependabot
```

I have not been able to find this functionality. Does it exist, is there another way around this, or would this be a welcome contribution?

Thanks!

**Comment by lonnylot** [comment]
Randomly I have the same feature request.

Our use case would be to exclude ones with the hotfix label.

**Comment by samson0v** [comment]
@jetersen, can you please provide us with any updates on this issue?

**Comment by cchanche** [comment]
Hey so I've recently seen what [`actions/labeler`](https://github.com/actions/labeler/) does, and here is what I have been refining as a refactor for label matching for categories. This could also be the groundwork for better `autolabeler` labeling logic.

I'll just paste it here for future me or whoever wants to work on this :

<details>
<summary>Label-based category matching (click to expand)</summary>

### Label-based category matching

You can categorize pull requests based on their labels using a flexible but simple matching syntax.

Each category can define **one or more label conditions**. All conditions inside a category must be satisfied for the PR to match that category.

```yaml
categories:
  - title: "Category title"
    labels:
      # ...label matching options go here
```

---

## 1. Simple label (legacy / shorthand)

The simplest form, kept for backward compatibility and convenience:

```yaml
categories:
  - title: "Bug fixes"
    label: "bug"
```

**Behavior:**

> If the PR has the label `"bug"`, then it matches this category.

Notes:

- `label: "foo"` is **equivalent to**:

  ```yaml
  labels:
    include-any: ["foo"]
  ```

- You can use either `label` or `labels`, but not both in the same category. If both are present, the config is invalid.

---

## 2. Standard label matching (recommended)

Use the `labels` object for clearer and more powerful matching. All keys are optional; you can use just the ones you need.

```yaml
categories:
  - title: "Example"
    labels:
      include-any:  ["bug", "frontend"]
      include-all:  ["api", "breaking-change"]
      exclude-any:  ["wontfix"]
      exclude-all:  ["legacy", "security"]
```

### 2.1. `include-any`

```yaml
include-any: ["bug", "frontend"]
```

**Meaning:**  
Match if the PR has **at least one** of these labels.

- PR labels: `["bug"]` → matches  
- PR labels: `["frontend", "docs"]` → matches  
- PR labels: `["docs"]` → does **not** match

This is the most common matcher: “match if any of these labels is present.”

---

### 2.2. `include-all`

```yaml
include-all: ["api", "breaking-change"]
```

**Meaning:**  
Match if the PR has **all** of these labels (it may have extra labels too).

Formally: `include-all ⊆ PR labels`.

- PR labels: `["api", "breaking-change"]` → matches  
- PR labels: `["api", "breaking-change", "backend"]` → matches  
- PR labels: `["api"]` → does **not** match  
- PR labels: `["breaking-change"]` → does **not** match  

Use this when a category requires a specific combination of labels.

---

### 2.3. `exclude-any`

```yaml
exclude-any: ["wontfix", "invalid"]
```

**Meaning:**  
Match only if the PR does **not** have any of these labels.

- PR labels: `["bug"]` → matches  
- PR labels: `["bug", "wontfix"]` → does **not** match  
- PR labels: `["invalid"]` → does **not** match  

This is useful to skip PRs with “negative” or “meta” labels.

---

### 2.4. `exclude-all`

```yaml
exclude-all: ["legacy", "security"]
```

**Meaning:**  
Match only if the PR does **not** have **all** of these labels together.

Formally: the PR must **not** satisfy `["legacy", "security"] ⊆ PR labels`.

- PR labels: `["legacy"]` → matches  
- PR labels: `["security"]` → matches  
- PR labels: `["legacy", "security"]` → does **not** match  
- PR labels: `["legacy", "security", "bug"]` → does **not** match  

Use this to block specific label combinations (e.g. “legacy security fixes go elsewhere”).

---

### 2.5. How simple matchers combine

All conditions under `labels` are combined with logical AND:

```text
A PR matches a category if:

  (include-any is not set OR PR has at least one label from include-any)
AND
  (include-all is not set OR PR has all labels from include-all)
AND
  (exclude-any is not set OR PR has none of the labels from exclude-any)
AND
  (exclude-all is not set OR PR does not have all labels from exclude-all)
```

Examples:

```yaml
labels:
  include-any:  ["bug", "frontend"]
  include-all:  ["api"]
  exclude-any:  ["wontfix"]
```

This means:

> PR must have `api`  
> AND it must have at least one of `bug` or `frontend`  
> AND it must not have `wontfix`.

- `["api", "bug"]` → matches  
- `["api", "frontend"]` → matches  
- `["api", "bug", "wontfix"]` → does **not** match  
- `["bug"]` → does **not** match (missing `api`)  

---

## 3. Advanced matching (optional)

For most setups, `include-*` and `exclude-*` are enough.  
For more control, you can enable **advanced** behaviors:

- Restrict PR labels to a whitelist for a category
- Match only an exact label combination

These options are opt-in and mutually constrained by validation.

### 3.1. `allow-only-these`

```yaml
allow-only-these: ["frontend", "ui"]
```

**Meaning:**  
The PR’s labels must all come from this list.

Formally: `PR labels ⊆ allow-only-these`.

- `["frontend"]` → matches (within the whitelist)  
- `["frontend", "ui"]` → matches  
- `["frontend", "bug"]` → does **not** match (`bug` is outside the list)  
- `["bug"]` → does **not** match  

You can combine this with `include-any` / `include-all` to further constrain:

```yaml
labels:
  allow-only-these: ["frontend", "ui"]
  include-any:      ["frontend"]
```

Meaning:

> Match PRs that are purely frontend/UI (no other labels),  
> and that have at least the `frontend` label.

---

### 3.2. `exact-labels`

```yaml
exact-labels: ["bug", "P1"]
```

**Meaning:**  
The PR must have **exactly** these labels and no others.

Formally: `set(PR labels) == set(exact-labels)`.

- `["bug", "P1"]` → matches  
- `["P1", "bug"]` → matches (order does not matter)  
- `["bug"]` → does **not** match  
- `["bug", "P1", "backend"]` → does **not** match  

This is useful if you need categories that only apply to very specific label combinations.

---

## 4. Validation rules and combinations

Configuration is validated to keep it consistent and predictable.

### 4.1. `label` vs `labels`

- You can use either `label: "foo"` or `labels: { ... }` in a category.
- Using both in the same category is **not allowed** and will cause a validation error.

### 4.2. Basic vs advanced fields

Inside `labels`, the following rules apply:

- All of these fields are **optional**:

  ```yaml
  include-any
  include-all
  exclude-any
  exclude-all
  allow-only-these
  exact-labels
  ```

- Each field, if present, must be a **non-empty array of strings**.

- `exact-labels` is **exclusive**:
  - When `exact-labels` is defined, it cannot be combined with `include-any`, `include-all` or `allow-only-these`.
  - You may choose to also disallow `exclude-*` with `exact-labels`, depending on your implementation. If allowed, they further restrict matches **after** the exact label check.

- `allow-only-these` and `exact-labels` cannot both be present.

You can think of the precedence like this:

1. If `exact-labels` is defined:
   - The category matches only PRs whose labels exactly equal `exact-labels`.
2. Else, if `allow-only-these` is defined:
   - The category matches only PRs whose labels are all within `allow-only-these`.
   - Within that, `include-*` and `exclude-*` are applied.
3. Else:
   - Only `include-*` and `exclude-*` determine the match.

---

## 5. Summary

You have three levels of complexity:

1. **Simplest (legacy shorthand)**

   ```yaml
   label: "bug"
   ```

2. **Standard (recommended)**

   ```yaml
   labels:
     include-any:  ["bug", "frontend"]
     include-all:  ["api"]
     exclude-any:  ["wontfix"]
     exclude-all:  ["legacy", "security"]
   ```

3. **Advanced (optional)**

   ```yaml
   labels:
     allow-only-these: ["frontend", "ui"]
     include-any:      ["frontend"]
     # or
     exact-labels: ["bug", "P1"]
   ```

Use level 1 or 2 for most cases; reach for level 3 only when you need whitelisting or exact label set matching.
</details>
