### ISSUE TITLE
Pre-release Includes PRs from Previous Pre-release

### ISSUE THREAD

**Issue by ndkhanh-axonivy** [release-drafter/release-drafter#1402]
**Description:**

When creating a new pre-release using Release Drafter, the generated release note includes all pull requests (PRs) from the previous pre-release. I expect that each pre-release should only include the PRs specific to that release and not carry over PRs from previous pre-releases.

**Problem:**

- The current pre-release includes PRs from the previous pre-release.
- The expected behavior is that each pre-release should only contain PRs that have been merged since the last pre-release.

**Steps to Reproduce:**

1. Create the first pre-release.
2. Merge several PRs after the first pre-release.
3. Create a new pre-release.
4. Observe that the new pre-release includes PRs from both the current and previous pre-releases.

**Expected Behavior:**

The new pre-release should only include PRs merged since the last release (pre-release or final release) and should not include PRs from previous pre-releases.

**Additional Information:**

I have attached an image showing the release notes for both the first and subsequent pre-releases. The image illustrates how PRs from the first pre-release are included in the second pre-release.

**Attachment:**

![image](https://github.com/user-attachments/assets/a26664fe-5163-4331-b725-2d07afd01b91)

**Configuration:**

Here’s the current configuration I’m using for Release Drafter:

```yaml

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
      prerelease:
        description: 'Is this a prerelease?'
        required: false
        default: 'false'
        type: boolean

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
          version: ${{ github.event.inputs.version }}
          prerelease: ${{ github.event.inputs.prerelease }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
