### ISSUE TITLE
How to categorize changes that don’t fall into any predefined category under the “Other” section?

### ISSUE THREAD

**Issue by acx10** [release-drafter/release-drafter#1439]
Hi, 

I am using Release Drafter and have categorized my release notes into several categories like Features, Bug Fixes, Refactoring, etc. However, I would like to know how to automatically categorize changes that don’t fall into any of these predefined categories into an “Other” section.

Alternatively, is there a way to display all the categories before the changes?

Thanks in advance for your help!

**Comment by cchanche** [comment]
Hey @acx10 

> Alternatively, is there a way to display all the categories before the changes?

What do you mean by that ?

As of support for "categorize changes that don’t fall into any of these predefined categories into an “Other” section.", you can do this with the `categories` config.

```yaml
categories:
  - title: 'Breaking'
    label: 'type: breaking'
  - title: 'New'
    label: 'type: feature'
  - title: 'Other Changes' # this will contain your uncategorized changes
```
