### ISSUE TITLE
Add git sha to the release template

### ISSUE THREAD

**Issue by brian-pickens** [release-drafter/release-drafter#1448]
I'd like to include the git sha of the version that triggered the run using the `github.sha` for the run in my release template. Specifically, I want to include it in my release name and release tag. My proposal is to add the sha to the following variables

|Variable | Description|
|-- | -- |
|$GIT_SHA_LONG| The full git sha from the `github.sha` context variable.|
|$GIT_SHA_SHORT| The short git sha (first 7 characters) of the `github.sha` context variable.|

**Comment by cchanche** [comment]
Hey @brian-pickens , thank you for this nice idea !

I would like our templates variables to stay in the scope of what release-drafter brings to the table, meaning metadata about code changes and the release process.

IMO, the `${{ github.sha }}` may not be too far of to qualify, and I would love to hear a bit more about your specific use-case for it.

What I can imagine you may be wanting to do with it is maybe generating a link for users to see the full changes between releases ? Here is hoiw I do it in my org : 

```yaml
# .github/release-drafter.yaml
name-template: "v$NEXT_MINOR_VERSION"
tag-template: "v$NEXT_MINOR_VERSION"
template: |
  # Changes

  ## Pull-requests

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$NEXT_MINOR_VERSION
```

For instance with this repo's releases : 

**Full Changelog**: https://github.com/release-drafter/release-drafter/compare/v6.2.0...v6.1.1

LMK @brian-pickens !
