### ISSUE TITLE
untagged-<HASH> being set as Tag name

### ISSUE THREAD

**Issue by nchudleigh** [release-drafter/release-drafter#204]
New drafts have their tag name being set as untagged-<HASH>

Our version tags are set as `v1.1.1-staging` and `v1.1.1-production`.

Looking through the code I can see that the `semver` package is used to parse the version out of the `lastRelease`'s tag name.  This seems to work fine when I test locally.

![image](https://user-images.githubusercontent.com/5580824/57400600-d9d81080-71a1-11e9-9da2-a9fdf5ed2706.png)

Here are my relevant settings
```yml
# release-drafter.yml
name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION-staging"
```

My thought is perhaps the NEXT_PATCH_VERSION variable is causing an error when I append the `-staging` to it.  If this is the case, how do I properly separate the two.
