### ISSUE TITLE
Date based releases?

### ISSUE THREAD

**Issue by whyman** [release-drafter/release-drafter#315]
We use a scheme that is pretty common of using the day of a release to tag it.

What work would need to be done to have this happen?

**Comment by casz** [comment]
You would need to implement some more logic here:

https://github.com/toolmantim/release-drafter/blob/864af063817df9c43c6f538364eec24d9fc3b1bc/lib/versions.js#L21-L34

**Comment by shadoath** [comment]
@jetersen Any example of how to make this happen?

**Comment by jetersen** [comment]
@shadoath currently not supported.
You would need to add the logic here:
https://github.com/release-drafter/release-drafter/blob/864af063817df9c43c6f538364eec24d9fc3b1bc/lib/versions.js#L21-L35

I imagine to would check if the template contains something like `$DATE` and than use the an new function that knows how to convert `$DATE` into a date version.
It should properly check the last release to support `20210210.1`, `20210210.2`, `20210210.3` so that you can release multiple times on the same date.

**Comment by jetersen** [comment]
Someone sad to see all these 👍 and no one implementing as it should be fairly simple to add.

**Comment by 0rax** [comment]
We implement a quick hack in a fork of ours here https://github.com/moneway/release-drafter/commit/82edd3e3a06863eab9797d1818a31690cbc907f1 to allow some version of calendar versioning in `release-drafter` though this is based on quite some old code.

I will take a look at updating this implementation and creating a PR here for that as I am currently migrating away from our fork and webhook based system and was going to fix this by implementing a custom version resolver as part of a Github Actions pipeline. If this can help others, it's better to have this as a feature instead of a hack.

As the change was pretty trivial, it might be quick to re-implement there, though, as far as I remember, I wasn't able to update the version number when new PRs came in.

**Comment by 0rax** [comment]
This issue is not as trivial as it seems in the end. Handling everything present on https://calver.org/ is pretty hard. Mainly handling formatting for incremental version specifier (i.e: MICRO version after a date such as `2021.01_1` for a `YYYY.0M_MICRO` template).

Handling a simple date-based system seems pretty easy, the addition of other identifier after that makes it way harder (especially with optional identifier that are only present when needed).

**Comment by jetersen** [comment]
Starting with something simple? Than if someone needs it they can contribute :)

**Comment by 0rax** [comment]
I might just commit what I have right now, which works pretty well and just does not handle optional identifier. I just have one small bug to squash out !

**Comment by 0rax** [comment]
I just commited my first implementation, it still needs some tests and documentation but feel free to check it out if are interested.

**Comment by leojonathanoh** [comment]
I have a test repo https://github.com/leojonathanoh/test-github-actions with both date-based and semver-based tags. I want to test migrating away from date-based to semver-based releases, so I now have semver tags on later commits than the latest date-based tag 

But every new draft created is still going by date-based versioning, tried a bunch of config options. How do i support the older date-based releases while still getting correct draft which are semver-based? I assume it's because the date-based `$MAJOR` i.e. `20210402` which is numerically larger than the largest semver's `$MAJOR` i.e. `0`, and this action determines the previous release by the largest `$MAJOR/$MINOR/$PATCH`, which ends up being a date-based tag.

**Comment by leojonathanoh** [comment]
i resorted to renaming all my calver tags to zYYYYMMDD.X.X and now the drafts are back to semver

**Comment by jetersen** [comment]
Perhaps this is best solved by an action step before?

You could expand the github action before to check for existing tag via

```
gh release view --json tagName
{
  "tagName": "2021.02.13"
}
```

```yaml
jobs:
  draft-release:
    runs-on: ubuntu-20.04
    steps:
      - name: Generate CalVer version
        id: calver
        run: |
          export VERSION=$(date "+%Y.%m.%d")
          echo ::set-output name=version::${VERSION}
          echo "Version set to ${VERSION}"
      - uses: release-drafter/release-drafter@v5
        with:
          tag: ${{ steps.calver.outputs.version }}
          name: ${{ steps.calver.outputs.version }}
          version: ${{ steps.calver.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
