### ISSUE TITLE
Please don't break of give a nice error message when using label for multiple labels

### ISSUE THREAD

**Issue by 304NotModified** [release-drafter/release-drafter#353]
This:

```
categories:
  - title: '🧰 Maintenance'
    label:
      - 'chore'
      - 'dependencies'
```

Will give the error

> Cannot read property 'title' of undefined

Proposal

- Don't care if `label` or `labels` is used, or
- Show a better error message

See also https://github.com/release-drafter/release-drafter/issues/320
