### ISSUE TITLE
[Error] probot 

### ISSUE THREAD

**Issue by caicaishmily** [release-drafter/release-drafter#362]
When I try add `release-drafter` in my `.yml` I got this error:
```
Invalid command receive,/app/index.js

Usage: probot <command> [options]

Options:
  -V, --version  output the version number
  -h, --help     output usage information

Commands:
  run            run the bot
  receive        Receive a single event and payload
  help [cmd]     display help for [cmd]
{ Deprecation: [@octokit/request-error] `error.code` is deprecated, use `error.status`.
    at RequestError.get (/app/node_modules/@octokit/request/node_modules/@octokit/request-error/dist-node/index.js:29:17)
    at loadYaml (/app/node_modules/probot-config/lib/index.js:51:11) name: 'Deprecation' }
11:13:07.934Z  INFO probot: caicaishmily/actions_for_angular: No valid config found

```
Here is the .yml file, , Is anybody face same problem ?
```yml
name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
