### ISSUE TITLE
Option for publishing release instead of a draft

### ISSUE THREAD

**Issue by bartaz** [release-drafter/release-drafter#427]
With Release Drafter as an GitHub action it would be quite useful to use it to actually publish a release instead of just a draft.

Would it be possible to add some parameter that will tell Release Drafter to publish the release instead of a (default) draft?

Something like:

```yml
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Alternatively it would be nice to "dry run" release drafter action and output the body of release notes, so it can be passed to something like [actions/create-release](https://github.com/actions/create-release)

```yml
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        id: drafter
        with:
          dry_run: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          body: ${{ steps.drafter.outputs.body }}
```
