### ISSUE TITLE
Not appending changes on second listed branch

### ISSUE THREAD

**Issue by madchap** [release-drafter/release-drafter#449]
Hi,

We've got release-drafter configured here with a very simple setup, configured on the repo's default branch `master`: https://github.com/DefectDojo/django-DefectDojo/blob/master/.github/workflows/release-drafter.yml

Snippet, should look familiar per the doc:
```
on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - master
      - dev
```

However, merges (any kind of merges) happening on the `dev` branch are not being appended to the draft, whereas merges on `master` work.

Is there something obvious that I am missing?

Thanks a lot.
