### ISSUE TITLE
couldn't get it to work

### ISSUE THREAD

**Issue by xenoterracide** [release-drafter/release-drafter#489]
no matter what I did I got this

```
  env:
    JAVA_HOME: /opt/hostedtoolcache/jdk/8.0.252/x64
    JAVA_HOME_8.0.252_x64: /opt/hostedtoolcache/jdk/8.0.252/x64
    GITHUB_TOKEN: ***
/usr/bin/docker run --name c1aea39d063b4d547eaa17999132cfcc668_ccf508 --label 430c1a --workdir /github/workspace --rm -e JAVA_HOME -e JAVA_HOME_8.0.252_x64 -e GITHUB_TOKEN -e INPUT_CONFIG-NAME -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/piccolo-smart-picc/piccolo-smart-picc":"/github/workspace" 430c1a:ea39d063b4d547eaa17999132cfcc668
19:23:41.117Z  WARN probot: piccolo-medical/piccolo-smart-picc: Invalid config file
  ValidationError: child "template" fails because ["template" is required]
      at Object.exports.process (/app/node_modules/@hapi/joi/lib/errors.js:202:19)
      at internals.Object._validateWithOptions (/app/node_modules/@hapi/joi/lib/types/any/index.js:763:31)
      at internals.Object.validate (/app/node_modules/@hapi/joi/lib/types/any/index.js:797:21)
      at validateSchema (/app/lib/schema.js:89:52)
      at getConfig (/app/lib/config.js:21:20)
      at async /app/index.js:16:20
19:23:41.128Z  INFO probot:
  piccolo-medical/piccolo-smart-picc: Config validation errors, please fix the following issues in release-drafter.yml:
  ┌──────────┬────────────────────────┐
  │ Property │ Error                  │
  ├──────────┼────────────────────────┤
  │ template │ "template" is required │
  └──────────┴────────────────────────┘
```      
this is my last attempt, but previous attempts didn't use the config name, and the filename was `.github/release-drafter.yml`

```
Calebs-MBP:.github calebcushing$ cat my-release-drafter.yml 
template: |
  # There's new stuff!
Calebs-MBP:.github calebcushing$ cat workflows/main.yml 
name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Gradle Wrapper
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/*.gradle/wrapper*') }}
          restore-keys: ${{ runner.os }}-gradle-wrapper
      - name: Gradle Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle/caches*') }}
          restore-keys: ${{ runner.os }}-gradle-caches
      - name: build
        run: ./gradlew -Dorg.gradle.daemon=false -Dskip-integration-tests=true clean build --info
      - name: assemble
        run: ./gradlew -Dorg.gradle.daemon=false assemble
      - name: finalize-build
        run: ./bin/finalize-build.sh $PWD piccolomed-smartpicc-android
      - run: find . -name "*.zip"
      - name: Create Release
        id: create_release
        uses: release-drafter/release-drafter@v5
        with:
          config-name: my-release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./build/piccolomed-smartpicc-android.zip
          asset_name: piccolomed-smartpicc-android.zip
          asset_content_type: application/zip
```
