### ISSUE TITLE
Commits get added to changelogs sometimes, but missing other times.

### ISSUE THREAD

**Issue by jmplummer** [release-drafter/release-drafter#493]
Has anyone had an issue where your commits sometimes are missing from the $CHANGES section of the template? They get added sometimes, but other times it just says "Nothing has changed" and we have to manually added changes. Workflow is the same for both cases, not sure whats happening. We are using the below template:

```
name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🧰 Maintenance"
    label: "maintenance"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
template: |
  **Release Date:** <DATE>
  **Release Engineer:** $CONTRIBUTORS
  **Previous Release:** $PREVIOUS_TAG

  ## What's Changed

  $CHANGES
```

**Comment by ja2-derek** [comment]
Seeing the same issue here.

I found that sometimes the `findCommitsWithAssociatedPullRequests` is not returning the latest commits.

**Comment by derekchan** [comment]
Seeing the same issue here.

I found that sometimes the `findCommitsWithAssociatedPullRequests` is not returning the latest commits.

**Comment by jmplummer** [comment]
So, I will say that we saw a drastic improvement when switching from the Github App to the Github Workflows/Actions. If you're already using that, I got nothing for you lol.

**Comment by jetersen** [comment]
The GitHub app seems to be resource limited at the moment 😓
At the moment is it running as a app in Heroku.
Was willing to look into spinning up as a function where it could much like a GitHub Action spinning up as needed.

**Comment by deivid-rodriguez** [comment]
I'm having the same issue while using `release-drafter` as a Github Action. Maybe it has to do with pagination and the limits set for the queries inside `findCommitsWithAssociatedPullRequests`? I was expecting `release-drafter` to automatically add all changes since the last release, but it seems to be always adding a different subset of the set of PRs it should be adding.

**Comment by lmagyar** [comment]
FYI: In our experience, the root cause can be, that PR's associated with commits are coming from GH's GraphQL API, and that needs some time to process the same event, that triggered the release drafter itself. We added a 15s delay before running the release drafter step, ugly but works. Later we put the release drafter as the last step of our CI, that means at least 1 minute delay.
```
      - name: Wait for 15 seconds to ensure GraphQL consistency
        shell: bash
        run: sleep 15s
```

**Comment by cchanche** [comment]
Thank you @lmagyar for useful feedback! Just for reference, by : 

> PR's associated with commits are coming from GH's GraphQL API

... you mean "PRs that were merged using GH's GraphQL API (fetched through commit history)" ? Is that Correct ?

If so, I assume your particular case featured programmatically-triggered merges in the same (or adjacent) GitHub Actions workflow release-drafter runs in. If so, it may be useful to issue a warning somewhere about it

**Comment by lmagyar** [comment]
> ... you mean "PRs that were created using GH's GraphQL API (fetched through commit history)" ? Is that Correct ?

No, I'm talking about the GraphQL query, where release-drafter searches for PRs that are associated with commits. And when it starts this GraphQL query, the very last/recent PR, that trigered the release drafter run, is not returned by this query. If we start the query (or the whole rel. drafter action) a few seconds later, the query returns even the very last/latest PR, that triggered the rel. drafter run.

**Comment by cchanche** [comment]
Ah I see, so this is less specific than what I originally thought.

Running release-drafter on a merge-commit trigger is quite common... there may be some investigation to do here !

Do you have a public repo featuring your particular situation ?

I feel this may be related to the volume of GitHub object already in the repo or the size of the pull request.. I fear a small reproduction repo might not do

Edit : thank you for your reply !

**Comment by lmagyar** [comment]
In our GH org, when we started to use rel.drafter, it missed the last/latest merge/PR nearly all the time, here are 2 repos: https://github.com/homeassistant-apps/app-cloudflared https://github.com/homeassistant-apps/app-newt

After we moved the rel. drafter action to the end of the whole CI workflow (that takes few minutes), no PRs were missed.

> there may be some investigation to do here !
> I feel this may be related to the volume of GitHub object already in the repo

One strange thing is that this GraphQL query runs approx. 1 minute, I have near zero experience with this API, but that seems to me quite long, maybe the query needs some optimization, but my GraphQL knowledge is de facto zero, so can't help in this regard.

**Comment by cchanche** [comment]
Ah very nice, I'll have a look at this ! 1min queries (REAST, GraphQL or sth else) are quite worrying 😅 

There is definitely some optimisation to do on release-drafter's part, and #1470 may be the start of something for this issue

**Comment by cchanche** [comment]
Hey, so I think this repo just experienced an instance of this issue :

I merged a PR, the first one since v6.1.1 was released, and draft-release for v6.1.2 was published empty.

The workflow run for it is [here](https://github.com/release-drafter/release-drafter/actions/runs/21210127633/job/61016252619). It's code looks like :

```yaml
name: Release Drafter

on:
  push:
    branches:
      - master

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

You'll notice relase-drafter runs immediately.

You'll also see I ran a second attempt on it 

<img width="285" height="168" alt="Image" src="https://github.com/user-attachments/assets/d875fc0d-8196-4c36-95f2-f4e4b30fa369" />

... and release v6.1.2 was magically updated with the missing PR : 

<img width="953" height="513" alt="Image" src="https://github.com/user-attachments/assets/475f1fc7-6c00-404b-b10b-91e706ffaadd" />

(i have no screenshot of the original empty draft-release)

Please confirm if this scenario fits the original issue or not. May also correspond to #871
