### ISSUE TITLE
Duplicates from multiple issue labels in separate categories

### ISSUE THREAD

**Issue by jonpas** [release-drafter/release-drafter#498]
Our configuration at https://github.com/acemod/ACE3 contains:
```yaml
categories:
  - title: '**IMPROVED:**'
    labels:
      - 'kind/enhancement'
  - title: '**CHANGED:**'
    labels:
      - 'area/compatibility'
```

Having an issue such as https://github.com/acemod/ACE3/pull/7571 labelled with both `kind/enhancement` and `area/compatibility` results in the change becoming drafted twice, once under each category.

Having an option to only pick the first category listed would be very useful for avoiding duplicates like that. I can see why some projects might want it logged in both cases as well.
