### ISSUE TITLE
Automatically set semver tag based on categories

### ISSUE THREAD

**Issue by jacobtomlinson** [release-drafter/release-drafter#518]
It would be great if instead of setting the tag template to something like `tag-template: 'v$NEXT_PATCH_VERSION'` you could have it choose the version based on categories.

For example the default template could be `v$NEXT_PATCH_VERSION` but if there are PRs in the "enhancement" category then the template should be `v$NEXT_MINOR_VERSION`.

**Comment by jetersen** [comment]
several PRs are already trying to address this. See #513

**Comment by jacobtomlinson** [comment]
Great thanks! I look forward to those being merged and released.

**Comment by jetersen** [comment]
Now possible to use `$RESOLVED_VERSION`
and adding desired labels to the `version-resolver` config
ie. something like this:
```yaml
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
```
