### ISSUE TITLE
Question - draft after release deleted is not working

### ISSUE THREAD

**Issue by mawkee** [release-drafter/release-drafter#527]
Consider this simple flow:
1. A PR is merged to the default branch
1. Release-drafter builds a new draft release with said PR
1. The Draft Release is published, with a tag is set for it (let's call it v1.1.1)
1. Someone deletes the v1.1.1 release

Now what should happen, ideally, is that a new flow is triggered by using the following statement on the release-drafter.yml file:

```yaml
on:
  push:
    branches:
      - master
  release:
    types: [deleted]
```

However, after doing that, the draft is not being built, without printing any messages whatsoever. By reading the code, I expected at least to see a message similar to `Ignoring push. :branch_name is not one of: [...]`. I've done some tests to check the context on which the action runs after the `release deleted` event, and it seems that it points to the tag (on this case, v1.1.1, same name as the release), but I'm not entirely sure how to deal with that.

Is there any good way to deal with this?

**Comment by jetersen** [comment]
#546 should fix the case as long as it points to git reference as you mentioned it points to `v1.1.1` :)

**Comment by jetersen** [comment]
You could even have it run the step with `publish` if `if: contains(github.ref, "ref/tags")`

```
name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - master
    tags:
      - v*
    release:
      types: [deleted]

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Draft Release
        uses: release-drafter/release-drafter@v5
        with:
          publish: ${{ contains(github.ref, "ref/tags") }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Funny enough this could partly enable #316 to work 😆
Since you could just repush all tags and watch Release Drafter go to party 😆
