### ISSUE TITLE
$NEXT_PATCH_VERSION is reset after publishing pre-release

### ISSUE THREAD

**Issue by pahan35** [release-drafter/release-drafter#537]
From time to time we publish pre-releases for dev/test purposes.

Unfortunately, after such releases, `$NEXT_PATCH_VERSION` is reset to `0.0.1`.
![image](https://user-images.githubusercontent.com/13823215/83043933-2b249d80-a04c-11ea-966b-72c00b5a23e9.png)

If it's hard to build correct version after such releases, I'd like to see an option to skip pre-releases to be counted as the previous release

## Which version is expected?
I expect to see version `v16.4.4`

## Which version I have?
Unfortunately, it's reset to `v0.0.1` :(

### release-drafter.yml
```
name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes
  $CHANGES
```
