### ISSUE TITLE
Allow to define category order/priority

### ISSUE THREAD

**Issue by mvorisek** [release-drafter/release-drafter#551]
This is a feature request to allow to set the category order/priority.

Very important to be able to move more important categories like "Breaking Changes" to the top of the changelog.

**Comment by jetersen** [comment]
That is done by ordering your categories.

Put the breaking category on top :)

https://github.com/release-drafter/release-drafter/blob/0c70ea335398cef92deec1d8fec2cb7721fe0383/.github/release-drafter.yml#L7-L19

**Comment by mvorisek** [comment]
> That is done by ordering your categories.
> 
> Put the breaking category on top :)
> 

That was the first idea that came to my mind, but ir did not work, see:
https://github.com/atk4/data/releases
https://github.com/atk4/data/blob/develop/.github/release-drafter.yml

**Comment by jetersen** [comment]
Yes uncategorized PRs are at the top.
I guess what your asking for is #139

**Comment by mvorisek** [comment]
Yes, exactly https://github.com/release-drafter/release-drafter/issues/139#issuecomment-480473934

Do you think this can be fixed soon and is there currently any workaround like specifying "other/unmatched labels"?

**Comment by jetersen** [comment]
You know you can just copy and paste? That's a quick workaround 😆

**Comment by mvorisek** [comment]
I mean without manual actual :D , only with the config..

**Comment by alfieyfc** [comment]
For a workaround that utilizes actions to automate this, I run this job on PR creation:
```yaml
    steps:
      # Label PR by head branch's name
      - name: Auto Labeler
        uses: TimonVS/pr-labeler-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Get length of labels array 
      - name: Get Labels
        id: get-label-arr
        run: |
          export LENGTH=$(curl -k https://api.github.com/repos/$GITHUB_REPOSITORY/pulls/${{ github.event.pull_request.number }} | jq '.labels | length')
          echo "::set-output name=length::$(echo $LENGTH)"
      # Label misc if no label was applied
      - name: Label Misc
        if: ${{ steps.get-label-arr.outputs.length == 0 }}
        uses: buildsville/add-remove-label@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          label: "type: misc"
          type: add
```
and put `type: misc` in the category at the bottom.

```yaml
# release-drafter.yml 
categories:
  - title: 🚀 Features
    label: feature
  - title: 🐛 Bug Fixes
    label: fix
  - title: Misc.
    label: "type: misc"
template: |
  $CHANGES
```

I guess there's a better way to inspect labeled labels than just checking the length of labels array, but this was probably already an overkill for a workaround and it fits my scenario for now so I'm just gonna stick with it 😆
