### ISSUE TITLE
Extends not working as expected

### ISSUE THREAD

**Issue by rodrigodiez** [release-drafter/release-drafter#561]
First and foremost thanks for your continued effort in supporting this great app! We love it! ❤️ 

We are having a problem to use the `_extends` Protobot feature, where it does not seem to work. We are using that feature in other apps - such as Settings - with no problems

Base file
```yml
# At gitub.com/my-org/protobot-config/release-drafter/base.yml
name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
categories:
  - title: "💥 Breaking Changes"
    labels:
      - "semver-major"
  - title: "🚀 Features"
    labels:
      - "semver-minor"
  - title: "🐛 Bug Fixes"
    labels:
      - "semver-patch"
  - title: "🧰 Maintenance"
    labels:
      - "chore"
      - "documentation"
      - "tests"
change-template: "- #$NUMBER $TITLE (@$AUTHOR)"
template: |
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS
```

File extending the base file
```yml
# At gitub.com/my-org/my-repo/.github/release-drafter.yml
_extends: protobot-config:release-drafter/base.yml
```

Workflow fails with the following message
```
10:01:56.747Z  WARN probot: my-org/my-repo: Invalid config file
  ValidationError: child "template" fails because ["template" is required]
      at Object.exports.process (/app/node_modules/@hapi/joi/lib/errors.js:202:19)
      at internals.Object._validateWithOptions (/app/node_modules/@hapi/joi/lib/types/any/index.js:763:31)
      at internals.Object.validate (/app/node_modules/@hapi/joi/lib/types/any/index.js:797:21)
      at validateSchema (/app/lib/schema.js:113:52)
      at getConfig (/app/lib/config.js:21:20)
      at async /app/index.js:18:20
10:01:56.760Z  INFO probot:
  my-org/my-repo: Config validation errors, please fix the following issues in release-drafter.yml:
  ┌──────────┬────────────────────────┐
  │ Property │ Error                  │
  ├──────────┼────────────────────────┤
  │ template │ "template" is required │
  └──────────┴────────────────────────┘
##[error]Invalid config file
```

Any idea?
