### ISSUE TITLE
Auto-Upload Build Artifacts to Release Assets

### ISSUE THREAD

**Issue by RehanSaeed** [release-drafter/release-drafter#565]
I'd like the artifacts from my latest CI build to automatically get uploaded to a GitHub releases assets. Is that something that could be added as a new feature? Or is there something existing I can use?

I was thinking that adding the name of a CI build you want to get artifacts from should be sufficient:

```yml
name: Release Drafter
on:
  push:
    branches:
      - master
jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
            artifactsFromBuild: 'BuildName'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by jetersen** [comment]
https://github.com/actions/upload-artifact is an option

**Comment by RehanSaeed** [comment]
Looks like I can do what I want with:

```yml
- uses: actions/download-artifact@v2
  with:
    name: my-artifact
    path: path/to/artifact
- uses: actions/upload-artifact@v2
  with:
    name: my-artifact
    path: path/to/artifact
```

Any chance this can be built in or should I just go with the above?
