### ISSUE TITLE
$CONTRIBUTORS variable takes contributors from a skipped PR

### ISSUE THREAD

**Issue by curquiza** [release-drafter/release-drafter#569]
Hello everyone, thanks for your useful tool!!! 😄 
In the [meilisearch organization](https://github.com/meilisearch/), we use release-drafter with GHA on most of our repositories for a few weeks and we are really satisfied!

I used to skip the PR of Dependabot thanks to the `exclude-labels:` field. It works perfectly: the PR is indeed not added to the release draft.

But the `dependatbot` contributor is still there.

<img width="1385" alt="Capture d’écran 2020-06-18 à 10 09 52" src="https://user-images.githubusercontent.com/20380692/84995087-defce280-b14b-11ea-93ad-5a1b03ec4a81.png">

Is it possible to include only contributors from non-skipped PR in the `$CONTRIBUTOR` variable?

FYI, here is my template:

```yaml
name-template: 'v$RESOLVED_VERSION 🐍'
tag-template: 'v$RESOLVED_VERSION'
exclude-labels:
  - 'skip-changelog'
version-resolver:
  minor:
    labels:
      - 'breaking-change'
  default: patch
categories:
  - title: 'Breaking changes'
    label: 'breaking-change'
template: |
  ## Changes

  $CHANGES

  Thanks again to $CONTRIBUTORS! 🎉
no-changes-template: 'Changes are coming soon 😎'
sort-direction: 'ascending'
```

Sorry if it's a duplicated issue but I found nothing.

Have a nice day!

**Comment by jetersen** [comment]
for a quick workaround you could use the replacers to get read of him 😅

**Comment by jetersen** [comment]
This regex would mostly do the job: `(?:and )?@dependabot-preview(?:\[bot\])?,?`

**Comment by curquiza** [comment]
Hello! Thanks for your quick answer.
I tried this, but it does not work. I probably did something wrong.
My template:

```yaml
name-template: 'v$RESOLVED_VERSION 🐍'
tag-template: 'v$RESOLVED_VERSION'
exclude-labels:
  - 'skip-changelog'
version-resolver:
  minor:
    labels:
      - 'breaking-change'
  default: patch
categories:
  - title: 'Breaking changes'
    label: 'breaking-change'
template: |
  ## Changes

  $CHANGES

  Thanks again to $CONTRIBUTORS! 🎉
no-changes-template: 'Changes are coming soon 😎'
sort-direction: 'ascending'
replacers:
  - search: '(?:and )?@dependabot-preview(?:\[bot\])?,?'
    replace: ''
```

(the `replace` is 2 single quotes)

The result:

<img width="1044" alt="Capture d’écran 2020-06-18 à 12 44 24" src="https://user-images.githubusercontent.com/20380692/85011167-74ef3800-b161-11ea-8de9-201ba88a6bf8.png">

**Comment by jetersen** [comment]
you have to write the full regex so:

```yaml
replacers:
  - search: '/(?:and )?@dependabot-preview(?:\[bot\])?,?/g'
    replace: ''
```
