### ISSUE TITLE
Suggestion for Multiple Packages

### ISSUE THREAD

**Issue by RehanSaeed** [release-drafter/release-drafter#575]
I have a [repo](https://github.com/Dotnet-Boxed/Framework/releases) which releases several packages using Git tags:

- Foo-1.2.3
- Bar-1.4.6

The tag contains the package name followed by the version number. I'd like release-drafter to draft a release for each of the packages above. If this is not possible, perhaps I can suggest a new `$PACKAGE_NAME` variable that can be used in the `tag-template` to determine the package name and version number.

```yml
name-template: '$PACKAGE_NAME $RESOLVED_VERSION'
tag-template: '$PACKAGE_NAME-$RESOLVED_VERSION'
change-template: '- $TITLE by @$AUTHOR (#$NUMBER)'
no-changes-template: '- No changes'
categories:
  - title: '🚀 New Features'
    labels:
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'maintenance'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  $CHANGES

  ## 👨🏼‍💻 Contributors

  $CONTRIBUTORS
```
