### ISSUE TITLE
Create an output for the resolved version number

### ISSUE THREAD

**Issue by jason-edstrom** [release-drafter/release-drafter#576]
It would be nice to have an output for the resolved version number to chain to deploy steps.

**Comment by jetersen** [comment]
I believe the action already outputs: `tag_name` which when using `tag-template: v$RESOLVED_VERSION` should have the desired effect?

**Comment by dreinon** [comment]
I personally use the following to get the version out of the tag:
```yml
            - name: Get tag assigned by release-drafter
              id: release_drafter
              uses: release-drafter/release-drafter@v5
              with:
                  config-name: release-drafter-config.yml
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Get version from tag
              id: version
              run: |
                  tag=${{steps.release_drafter.outputs.tag_name}}
                  echo "::set-output name=version::${tag#v}"

            - name: Use version output
              run: echo "${{steps.version.outputs.version}}"
```

**Comment by jetersen** [comment]
closing as this already possible

**Comment by andrey-helldar** [comment]
In my case, the Release Drafter is in an reusable workflow. Since the problem is similar, but not exactly, I'll write here the solution to my problem in case it helps someone else.

So, the Release Drafter startup crypt is in the [shared repository](https://github.com/TheDragonCode/.github/edit/main/.github/workflows/release-drafter.yml) and has the following additions as opposed to the "original" (changes noted with comments):

```yml
name: Release Drafter

on:
  workflow_call:
    outputs:                                        # that one
      tag_name:                                     # that one
        description: "Tag name"                     # that one
        value: ${{ jobs.draft.outputs.tag_name }}   # that one

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  draft:
    name: Release Draft
    runs-on: ubuntu-latest

    outputs:
      tag_name: ${{ steps.drafter.outputs.tag_name }}

    steps:
      - id: drafter                                 # that one
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Since I only need a value for "tag_name", I defined it. But you can easily list any of them.

So, getting these values is easy and simple:

```yml
name: Release Drafter

on:
  workflow_dispatch:

jobs:
  draft:
    uses: TheDragonCode/.github/.github/workflows/release-drafter.yml@main

  build:
    needs: draft

    name: App
    uses: TheDragonCode/github-notifications/.github/workflows/build.yml@main
    with:
      tag: ${{ needs.draft.outputs.tag_name }}

  ## This block I removed from the final file.
  ## It was added for the purpose of verifying that the information was received.
  info:
    runs-on: ubuntu-latest
    needs: draft
    steps:
      - run: echo "TAG is ${{ needs.draft.outputs.tag_name }}"
```

Result:

![image](https://github.com/release-drafter/release-drafter/assets/10347617/b3062f6d-4d16-4abd-872f-e0c76135aeea)

This way, I can easily use the resulting value wherever needed. For example, [here](https://github.com/TheDragonCode/github-notifications/blob/main/.github/workflows/release-drafter.yml).

To find a solution to this problem, [this article](https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-outputs-from-a-reusable-workflow) helped me.
