### ISSUE TITLE
What's changed since latest **public**

### ISSUE THREAD

**Issue by vslynko** [release-drafter/release-drafter#579]
Now the list of changes is formed from all PRs merged since the last release, no matter whether it's a pre-release or public release.
It may be useful to compile a list of changes since latest **public** release. To keep track of all items that are going to be publicly released.

```yaml
...
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

use-latest-public: true # defaults to false

categories:
  - title: '🚀 Features'
...
```
