### ISSUE TITLE
Change template variable URL doesn't get substituted

### ISSUE THREAD

**Issue by leouieda** [release-drafter/release-drafter#593]
First of all, thank you for making this! 

I've been trying to use the `$URL` variable in the `change-template` but it doesn't seem to get replaced by the actual PR URL. This is the draft release that's being generated:

![missing-url](https://user-images.githubusercontent.com/290082/87800868-db41a600-c846-11ea-8f55-b0e9acfee697.jpg)

The main reason I want it is so that I can copy the Markdown directly to the project website without having to replace the `#123` with actual links.

Below is my configuration file:

```
# Configuration for the Release Drafter workflow
name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
change-template: '* $TITLE (#$NUMBER $URL by [@$AUTHOR](https://github.com/$AUTHOR))'
categories:
  - title: 'New functions/classes'
    label: 'feature'
  - title: 'Enhancements'
    label: 'enhancement'
  - title: 'Bug Fixes'
    label: 'bug'
  - title: 'Deprecations'
    label: 'deprecation'
  - title: 'Documentation'
    label: 'documentation'
  - title: 'Maintenance'
    label: 'maintenance'
exclude-labels:
  - 'skip-changelog'
template: |
  [![DOI](https://zenodo.org/badge/DOI/PASTE_DOI_HERE.svg)](https://doi.org/PASTE_DOI_HERE)
  ## Highlights
  * DELETE IF THERE ARE NO HIGHLIGHTS
  $CHANGES
  This release contains contributions from: $CONTRIBUTORS
```
