### ISSUE TITLE
$CONTRIBUTORS includes authors of excluded PRs

### ISSUE THREAD

**Issue by leouieda** [release-drafter/release-drafter#594]
The `$CONTRIBUTORS` variable seems to be including authors of PRs excluded using `exclude-labels`. For example:

![missing-url](https://user-images.githubusercontent.com/290082/87801394-92d6b800-c847-11ea-94f8-1a1559aa6593.jpg)

Notice that `@fatiando-bot` isn't included in the changelog but shows up in the contributors list.

With configuration:

```
# Configuration for the Release Drafter workflow
name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
change-template: '* $TITLE (#$NUMBER $URL by [@$AUTHOR](https://github.com/$AUTHOR))'
categories:
  - title: 'New functions/classes'
    label: 'feature'
  - title: 'Enhancements'
    label: 'enhancement'
  - title: 'Bug Fixes'
    label: 'bug'
  - title: 'Deprecations'
    label: 'deprecation'
  - title: 'Documentation'
    label: 'documentation'
  - title: 'Maintenance'
    label: 'maintenance'
exclude-labels:
  - 'skip-changelog'
template: |
  [![DOI](https://zenodo.org/badge/DOI/PASTE_DOI_HERE.svg)](https://doi.org/PASTE_DOI_HERE)
  ## Highlights
  * DELETE IF THERE ARE NO HIGHLIGHTS
  $CHANGES
  This release contains contributions from: $CONTRIBUTORS
```

Note: this is the same code and example from #593 but I thought it would be best to open another issue since it's a separate problem.
