### ISSUE TITLE
Complains about missing template

### ISSUE THREAD

**Issue by mrchief** [release-drafter/release-drafter#603]
I tried v5 and v5.11.0.

**on develop (with develop as default branch)**

```
name: Release Drafter

on:
  push:
    branches:
      - develop

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Draft Release
        uses: release-drafter/release-drafter@v5.11.0
        with:
          config-name: .github/release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

![image](https://user-images.githubusercontent.com/781818/88467045-b67dac00-cea0-11ea-82d4-d2a6eb19973b.png)

![image](https://user-images.githubusercontent.com/781818/88467090-2429d800-cea1-11ea-9179-290dbbc2133a.png)

_(And I have tried the same on master branch as well.)_

**release-drafter.yml**
```
name-template: "v$RESOLVED_VERSION 🌈"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "✨ Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    label: "fix"
  - title: "📚 Documentation"
    label: "docs"
  - title: "✅ Tests"
    label: "docs"
  - title: "🧰 Maintenance"
    labels:
      - "chore"
      - "ci"
      - "refactor"
      - "build"
      - "revert"

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
template: |
  ## Changes

  $CHANGES
```

These are some of the other configs I tried but I get the same error everytime.

**without custom config**
```
name: Release Drafter

on:
  push:
    branches:
      - develop

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Draft Release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**on master** (master default branch)
```
name: Release Drafter

on:
  push:
    branches:
      - master

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Draft Release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by jetersen** [comment]
is it a private repo?

**Comment by mrchief** [comment]
@jetersen yeah.

**Comment by jetersen** [comment]
@mrchief can you try and create a token with repo permissions and use that instead of `${{ secrets.GITHUB_TOKEN }}`

You can add the token as a secret and use another name.

You can add secrets to a repo under settings > secrets

**Comment by mrchief** [comment]
I tried with a repo access token but the error remains.

```
      - name: Draft Release
        uses: release-drafter/release-drafter@v5.11.0
        with:
          config-name: .github/release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
```
