### ISSUE TITLE
Branch specific configuration?

### ISSUE THREAD

**Issue by joakime** [release-drafter/release-drafter#656]
It would be nice if release-drafter has the ability to specify multiple configurations with different `target-branch` to manage multiple branches in parallel.

This is a concept seen on other actions, like dependabot.

An example of this for dependabot is can be seen at https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/.github/dependabot.yml

Looks like ...

``` yml
version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "jetty-9.4.x"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "jetty-9.4.x"

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "jetty-10.0.x"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "jetty-10.0.x"

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "jetty-11.0.x"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "jetty-11.0.x"
```

If release-drafter supported this `target-branch` concept, then it could be configured to manage multiple active releases in larger projects that have multiple active branches all with interleaved releases.
