### ISSUE TITLE
Release drafter doesn't generate anything

### ISSUE THREAD

**Issue by ilopmar** [release-drafter/release-drafter#671]
We have been using this tool for a while but now it doesn't generate anything and there is no output so we can't debug what's going on.

You can see that it run here https://github.com/micronaut-projects/micronaut-openapi/runs/1213542946?check_suite_focus=true#step:7:6 but there is no output and no draft release generated.

This worked in the past because we generate releases like https://github.com/micronaut-projects/micronaut-openapi/releases/tag/v1.5.3

Any idea how to debug this? Is there any flag we can include so it is more verbose and we can see what's going on?

**Comment by jetersen** [comment]
Your using a custom github token? Perhaps you accidently removed that secret or expired the token?

**Comment by alvarosanchez** [comment]
No, we use an organization secret to store it and it is working fine across 70+ repos.

**Comment by jetersen** [comment]
Atm the trigger only happens on push, and your action was running on pull request.
![image](https://user-images.githubusercontent.com/1661688/95887517-391b5680-0d80-11eb-8451-5bab5a8564f8.png)

I started #667 to prepare for #549
The reason for #549 is to dedicated code for GitHub action that behaves differently.

**Comment by Juanpe** [comment]
Hi! I have the same issue, I'm trying to get the resolved version to chain some steps, but the release drafter's output is null. 

This is sample of my workflow code:
```yaml
    steps:
     - name: update_release_draft
       id: update_release_draft
       uses: release-drafter/release-drafter@master
       env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
     - name: Show output
       run: |
         echo ${{ steps.update_release_draft.upload_url }}
         echo ${{ steps.update_release_draft.name }}
```

and the log is this:
<img width="434" alt="Screenshot 2021-02-10 at 08 27 02" src="https://user-images.githubusercontent.com/1409041/107478461-ca0d0d80-6b79-11eb-8554-6f2c1552b891.png">

I'm missing anything? 

Thanks in advance :)

**Comment by jetersen** [comment]
@Juanpe not sure how I can help. Is this a private repo?

**Comment by Juanpe** [comment]
No, it's public, you can see the workflow here: https://github.com/Juanpe/SkeletonView/blob/main/.github/workflows/release.yml

I've setting the next version using an input field, but I would like to release the version, obtain the resolved version in order to update the podfile and the publish the library. 

So, the workflow should look like this:
```yaml
    create_release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: publish release
              uses: release-drafter/release-drafter@v5
              id: update_release_draft
              with: 
                publish: true
              env:
                 GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    bump_pod_version:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: setup fastlane
            run: brew install fastlane
          - name: bump version
            run: fastlane bump_version next_version:${{ steps.update_release_draft.name }}
          - name: commit changes
            uses: stefanzweifel/git-auto-commit-action@v4
            with:
              branch: 'main'
              commit_message: 'Bump version ${{ steps.update_release_draft.name }}'
            env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
```

but `${{ steps.update_release_draft.name }}` is empty

**Comment by jetersen** [comment]
You have to share the steps between jobs.
This is not done by default.
https://docs.github.com/en/actions/guides/storing-workflow-data-as-artifacts#passing-data-between-jobs-in-a-workflow

**Comment by lihuacai168** [comment]
I also encountered the same situation.
There is three commits in  v.1.0.2,but change log is empty.
Is it because the commit tags don't match the labels?
@ilopmar 
- commit log
```
feat: 测试获取release获取v1.0.2
a63e0b5
@lihuacai168
feat: 测试先推送在打tag
9dcd618
@lihuacai168
feat: 测试master push发布
```
- my [labels](https://github.com/lihuacai168/godis/blob/master/.github/release-config.yml)
```
name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🌱 新功能 Features'
    labels:
      - 'feature'
      - 'enhancement'
      - 'feat'
      - '新功能'
  - title: '🚀 性能优化 Optimization'
```

- [release v1.0.2](https://github.com/lihuacai168/godis/releases/tag/v1.0.2)
![image](https://user-images.githubusercontent.com/11568297/111097928-75482280-857d-11eb-8c63-2c73fdc6770f.png)


- [release-drafter log](https://github.com/lihuacai168/godis/runs/2101622247?check_suite_focus=true)
```
Run release-drafter/release-drafter@v5
  with:
    config-name: release-config.yml
    version: v1.0.2
    tag: v1.0.2
  env:
    GITHUB_TOKEN: ***
lihuacai168/godis: Found 9 releases
{ name: 'event', id: '648743383' }
lihuacai168/godis: No draft release found
{ name: 'event', id: '648743383' }
lihuacai168/godis: Last release: v1.0.1
{ name: 'event', id: '648743383' }
lihuacai168/godis: Fetching all commits for reference refs/tags/v1.0.2 since 2021-03-13T09:01:22Z
{ name: 'event', id: '648743383' }
lihuacai168/godis: Creating new release
{ name: 'event', id: '648743383' }
```
