### ISSUE TITLE
What level of access is required for the GITHUB_TOKEN

### ISSUE THREAD

**Issue by IEvangelist** [release-drafter/release-drafter#688]
Hi friends 👋🏽,

Thank you so much for creating this awesome GitHub action, looks amazing. Cannot wait to try it out. I was trying to look for what level of access is required for the `GITHUB_TOKEN`. I couldn't find it, so I'm asking here.

What boxes should be checked for the token creation?

![image](https://user-images.githubusercontent.com/7679720/97013590-d3ad2f80-150e-11eb-8d4b-1bb37daa36ef.png)

**Comment by jetersen** [comment]
The default github action should have sufficient permission.

**Comment by IEvangelist** [comment]
So, there is no need to pass in the `secrets.GITHUB_TOKEN`?

```yml
jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

My repo doesn't have any secrets yet, so I assumed that since this was not optional I needed to create one. But I do not know which  checkboxes to select.
