### ISSUE TITLE
Use Personal Access Token instead of GITHUB_TOKEN?

### ISSUE THREAD

**Issue by gvolpe** [release-drafter/release-drafter#768]
Hi, 

Is it possible to use a Personal Access Token for this action? I created a `GH_PAT` secret with my access token as the value but it seems this action does not pick it up. This is what I have.

```yaml
jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5.13.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PATH }}
```

The reason why I need a personal token is so this workflow can trigger another workflow (release on tag creation), which is not supported by `GITHUB_TOKEN`. More details about this here, if interested: https://github.community/t/triggering-a-new-workflow-from-another-workflow/16250

Here are two pipelines where it failed: 

- https://github.com/cr-org/neutron/runs/1776899406
- https://github.com/cr-org/neutron/runs/1776989504
