### ISSUE TITLE
Running workflow via a scheduled job fails

### ISSUE THREAD

**Issue by mattnydam** [release-drafter/release-drafter#783]
When running `release-drafter@v5` via a scheduled job, we receive this error: 

```
Run release-drafter/release-drafter@v5
  with:
    config-name: release-drafter.yml
  env:
    GITHUB_TOKEN: ***
Error: Invalid config file
Error: context.repo() is not supported for this webhook event.
Error: Invalid config file
```

Our config file is most definitely valid as this same workflow will successfully run when we have it set to run on push or pr. 

For clarity, here is **failing** workflow:

```
name: Draft Release

on:
  schedule:
    - cron: '30 22 * * *'
  workflow_dispatch:

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "main"
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```

and here is the same workflow with a modified schedule, which **succeeds**:

```
name: Draft Release

on:
  push:
    branches:
      - main

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
