### ISSUE TITLE
Leading / for autolabel regexes

### ISSUE THREAD

**Issue by Zethson** [release-drafter/release-drafter#808]
Dear developers,

the documentation for the autolabelling states for example:

```
autolabeler:
  - label: 'chore'
    files:
      - '*.md'
    branch:
      - '/docs{0,1}\/.+/'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
    body:
      - '/JIRA-[0-9]{1,4}/'
```

Are the leading slashes for branches just a naming convention or do the regexes always require a leading slash?

I personally would name my branches feature/bla or fix/bla and not /feature/bla
