### ISSUE TITLE
Category label precedence

### ISSUE THREAD

**Issue by asbjornu** [release-drafter/release-drafter#811]
With `categories: labels:` it's possible to configure the mapping between labels and categories. For pull requests with multiple labels that subsequently make them fit into several categories, I can't seem to figure out the precedence of the label categorization. Some pull requests end up in several categories, other ends up in the "wrong" category (where `Bug fixes` would be preferable to `Documentation`, for instance).

Is it possible to exclude labels from a category, state that when a category is applied, don't apply any other categories, or otherwise affect the label-based categorization?

**Comment by jetersen** [comment]
The logic is a PR can end up in multiple categories for different reason as this is meant to be a draft. You may want to update text once the draft is done.

release-drafter to my knowledge should not put something into a category wrongfully as it will pull in labels for each PR and put the PR title into the respective category based on labels.

**Comment by asbjornu** [comment]
Yes, that makes sense @jetersen. But it would be nice to be able to say "only apply one category per PR" or something similar, to avoid duplicate entries in the release notes.

**Comment by jetersen** [comment]
Well what category should take precedence? 😓 

PRs are welcome 😅

**Comment by asbjornu** [comment]
> Well what category should take precedence? 😓

The order they are listed in `release-drafter.yml`, for instance? Once a matching category is applied, the matching issue is taken out of the list of issues to categorize.

> PRs are welcome 😅

Cool, I'll have a look when time permits.

**Comment by jetersen** [comment]
> The order they are listed in release-drafter.yml, for instance? Once a matching category is applied, the matching issue is taken out of the list of issues to categorize.

Ya, that makes sense 😅

> Cool, I'll have a look when time permits.

Great 👏

**Comment by jetersen** [comment]
This was fixed in #412

**Comment by asbjornu** [comment]
@jetersen, how does this work? With the following `release-drafter.yml` configuration, dependencies labeled both `dependency` and `development` are listed twice in the release notes:

```yaml
name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
categories:
- title: '⬆️ Dependencies'
  labels: [dependency]
- title: '🖋 Documentation'
  labels: [documentation]
- title: '🐛 Bug Fixes'
  labels: [fix]
- title: '📝 Configuration'
  labels: [config]
- title: '👩🏻‍💻 Development'
  labels: [development]
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
version-resolver:
  default: minor
template: |
  <!-- REMEMBER TO ADJUST THE VERSION NUMBER AND TAG BEFORE PUBLISHING! -->

  $CHANGES
```

I would think that since `labels: [dependency]` comes before `labels: [development]`, the issues matching both labels should only show up in the `Dependencies` category. That does not seem to be the case.
