### ISSUE TITLE
Readme example has outdated "disable-autolabeler"

### ISSUE THREAD

**Issue by shadycuz** [release-drafter/release-drafter#812]
Using the steps from the readme I got this in my workflow run:

> Warning: Unexpected input(s) 'disable-autolabeler', valid inputs are ['config-name', 'name', 'tag', 'version', 'publish', 'prerelease', 'commitish']

**Comment by jetersen** [comment]
More like action.yaml is outdated ;)

**Comment by shadycuz** [comment]
@jetersen I'm using the example from the readme and it does not work

```
- uses: release-drafter/release-drafter@v5
        # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
        # with:
        #   config-name: my-config.yml
        #   disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
