### ISSUE TITLE
No draft release created

### ISSUE THREAD

**Issue by shadycuz** [release-drafter/release-drafter#813]
Settings:

```
- name: Create Draft Release
        uses: release-drafter/release-drafter@v5.12.1
        with:
          disable-autolabeler: true
          tag: ${{ steps.snapshot_tag.outputs.tag }}
          version: ${{ steps.snapshot_tag.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Logs from worflow:
```
Warning: Unexpected input(s) 'disable-autolabeler', valid inputs are ['entryPoint', 'args', 'config-name', 'name', 'tag', 'version', 'publish', 'prerelease']
Run release-drafter/release-drafter@v5.12.1
  with:
    disable-autolabeler: true
    tag: 0.2.6-SNAPSHOT
    version: 0.2.6-SNAPSHOT
    config-name: release-drafter.yml
  env:
    GITHUB_TOKEN: ***
/usr/bin/docker run --name e4c77ba0fff9c94e188e9525dc24d6538b_20996c --label 5588e4 --workdir /github/workspace --rm -e GITHUB_TOKEN -e INPUT_DISABLE-AUTOLABELER -e INPUT_TAG -e INPUT_VERSION -e INPUT_CONFIG-NAME -e INPUT_NAME -e INPUT_PUBLISH -e INPUT_PRERELEASE -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/jenkins-std-lib/jenkins-std-lib":"/github/workspace" 5588e4:c77ba0fff9c94e188e9525dc24d6538b
```

I having nothing new under "Releases", unless that have moved draft releases somewhere else now. 

The config file is directly from the README:

```yaml

name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES
  ```

**Comment by shadycuz** [comment]
I have change config file to:

```
template: |
  ## Changes

  $CHANGES
  ```
  
  Still no draft releases created.

**Comment by jetersen** [comment]
Is this a public repo? Can you provide a repro?

**Comment by shadycuz** [comment]
@jetersen I thought I had, but maybe that was in another issue. An example run can be found here https://github.com/DontShaveTheYak/jenkins-std-lib/runs/2093878720?check_suite_focus=true

The drafter action runs, makes no output and no draft release. If I had to guess, its because I'm running release drafter on merged to my `develop` branch instead of master.

**Comment by jetersen** [comment]
The default branch is used for pulling the config.

**Comment by shadycuz** [comment]
I believe at that time it did have the config on it. I would have to have to go back and look later. But I did eventually get the config into the default branch and it was still not making draft releases.

**Comment by shadycuz** [comment]
@jetersen 

That might be the problem, it looks like by the time I got the settings in the default branch that I had removed the release drafter action from my actions file 🤔 

Let me retry tomorrow and it fixed I will close this issue.

**Comment by shadycuz** [comment]
@jetersen I set it back up today and no luck. 

Here is the workflow run: https://github.com/DontShaveTheYak/jenkins-std-lib/runs/2119405117?check_suite_focus=true

Here is the config from master:
`cat .github/release-drafter.yml`
```yml
template: |
  ## What’s Changed

  $CHANGES
```

Still no output in the workflow run and still no release draft created.

**Comment by jetersen** [comment]
@shadycuz for sanity could you try to use a regular push event or manual trigger instead of your fancy workflow? :)

**Comment by jetersen** [comment]
Also do you mind updating the version? of release drafter, your currently using v5.12.1

**Comment by jetersen** [comment]
FYI v5.12.1 only supports push events... hint read the release notes: https://github.com/release-drafter/release-drafter/releases/tag/v5.13.0

**Comment by shadycuz** [comment]
Well I'm not sure its that fancy, it's running on pull_request --> closed. I don't really want to change the workflow much. I could probably create a new one for debugging. 

I'm not exactly sure its expected to read release notes. I followed the readme exactly, I used the latest release mentioned here https://github.com/marketplace/actions/release-drafter

**Comment by jetersen** [comment]
I don't have access to push to marketplace @toolmantim 😓

**Comment by jetersen** [comment]
Marketplace is just a fancy storefront, you should look at the tags and branches the repo has.

**Comment by jetersen** [comment]
If you update to v5.14.0 I think your "fancy" workflow should work.

**Comment by shadycuz** [comment]
@jetersen I dont really understand how the other parts of my workflow are relevant to this discussion. I'm also quite surprised that a member of the jenkins org finds my little yaml workflow as "fancy". 

I think instead of asking the users to read every release note in github before using the software it might have made more sense for @rofafor to update the version in the example workflow when he added the `pull_request` events. 

While I didn't enjoy our interaction, your insights did allow me to get the software working. So thanks for that.

**Comment by jetersen** [comment]
@shadycuz okay you ask me to read your workflow files, but I cannot ask you to check if a newer version exists. That really doesn't seem fair. Sorry if my word choice "fancy". I was simply asking if you could try and debug the issue.

Sometimes text doesn't translate emotion well. My only attempt was trying to provide guidance.

**Comment by jeacott1** [comment]
I'm also seeing something similar, also on pull_request, but my issue is that I already have a pre-release including tag (not a draft anymore).
with the tag and name specified the same as the existing pre-release release-drafter is creating a brand new draft with the same name and tag as the existing one:
I'd expect it to find the existing release and update it.

```
      uses: release-drafter/release-drafter@v5.15.0
      with:
         version: "v${{ steps.get-coords.outputs.version }}"
         name: "v${{ steps.get-coords.outputs.version }}"
         tag: "v${{ steps.get-coords.outputs.version }}"
```


```
xx/build-test: Found 4 releases
{ name: 'event', id: '725157920' }
xx/build-test: No draft release found
{ name: 'event', id: '725157920' }
xx/build-test: Last release: v0.0.1
{ name: 'event', id: '725157920' }
xx/build-test: Fetching all commits for reference refs/pull/5/merge since 2021-04-07T06:51:09Z
{ name: 'event', id: '725157920' }
xx/build-test: Creating new release
{ name: 'event', id: '725157920' }
```
