### ISSUE TITLE
Support to create/update CHANGELOG.md file on Release?

### ISSUE THREAD

**Issue by Andre601** [release-drafter/release-drafter#866]
Would be really useful if this action would also have a way to update or create (when not available) a CHANGELOG.md file with the release notes when the release was actually published.
This would help a lot in keeping both the release AND the changelog up to date without fearing to miss the other.

**Comment by ssbarnea** [comment]
I think that we can take this at a new level and propose having a check action that auto-updates the changelog file. For example pre-commit tool is able to auto-fix PRs with minor issues like extra newlines or doing black reformatting for python code.

If we could make use of release drafter action that also updates in-repo changelogs, we could be sure that we do not merge changes that miss to report important changes (obviously that a change that does have a skip-changelog label would tell it not to update it).

The downside of this is that this pipeline may run quite often as it needs to run on PR edit, changing labels or title may create a need to update the changelog.

**Comment by Andre601** [comment]
One problem I now see is, how the changelog update would be handled.

Like, should the changelog be updated all the time similar to a release or should it be updated on a specific branch and a PR created?

**Comment by jetersen** [comment]
This is fully support. You can use the action's output to do this:

```yaml
      - name: Generate cumulative notes in automatic output-only mode
        id: release_drafter
        uses: release-drafter/release-drafter@feat/resolve-tag-commitish
        with:
          publish: true
          version: ${{ steps.version.outputs.version }}
          name: v${{ steps.version.outputs.version }}
          tag: v${{ steps.version.outputs.version }}
          header: '# Changelog'
          footer: ${{ steps.prior_changelog.outputs.footer }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Safely write exact action body
        env:
          RELEASE_BODY: ${{ steps.release_drafter.outputs.body }}
        run: |
          printf '%s' "${RELEASE_BODY}" > CHANGELOG.md
```

You can use a prestep to collect the changelog.md into the footer
Or a post step to prepend the release drafter into the changelog.md

I don't think it is needed for the action to do this directly it is not a lot of extra code to put it into CHANGELOG.md
