### ISSUE TITLE
What GitHub Actions `permissions` does Release Drafter Need

### ISSUE THREAD

**Issue by RehanSaeed** [release-drafter/release-drafter#869]
GitHub has released new `permissions` for GitHub actions. You can make a repo/organisation default to minimal read only permissions by default which causes release drafter to stop working. What permissions does release deafter need?

https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/

**Comment by jetersen** [comment]
Your welcome to experiment 😅

I presume contents write and pull request read

**Comment by RehanSaeed** [comment]
That worked, thanks!

```yaml
permissions:
      contents: write
      pull-requests: read
```
