### ISSUE TITLE
push tags action doesn't run when publishing draft release

### ISSUE THREAD

**Issue by jdforsythe** [release-drafter/release-drafter#876]
We're using release-drafter to create draft releases. When I have merged all the PRs down and edit the release and publish it, the `on: push: tags: -v*` action for our CI doesn't execute, so our Docker image isn't published

It runs without issue if I create the release from scratch, or if I delete the release and tag and create a new release from scratch

.github/workflows/release-drafter.yml

```yml
name: Release Drafter

on:
  push:
    branches:
      - master

  ## required for auto labeler
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

.github/workflows/docker-build.yml

```yml
name: Build Docker Image

on:

  push:
    ## on all version tags
    tags:
      - v*

  ## on all pull requests (create, update, synchronize)
  pull_request:

## ...

jobs:

  ## build and publish image
  publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
```

**Comment by jdforsythe** [comment]
The trick here is that apparently switching from a draft release to a published released doesn't trigger a tag push event (even though the UI says it will push a new tag, and the new tag appears).

So the way we solved this was by listening instead for the release event with type "published":

```yml

name: Build Docker Image

on:

  release:
    types: [published]
```

which seems to work fine. This may be a bug with GitHub Actions? But in any case, it might be nice to add this tip to the documentation
