### ISSUE TITLE
Creates release with empty changes section.

### ISSUE THREAD

**Issue by shadycuz** [release-drafter/release-drafter#883]
You can find the actions run [here](https://github.com/DontShaveTheYak/jenkins-std-lib/runs/2744450491?check_suite_focus=true).

The release draft looked perfect. All it needed to do was change the draft to a actual release. Not sure what happened but it didn't leave any error output or anything. 

I'm going to manually fix the release but here is what it created.

![image](https://user-images.githubusercontent.com/17090999/120775312-1695a380-c4f1-11eb-827f-ec94161d251b.png)

**Comment by shadycuz** [comment]
Seeing this on multiple repos of mine.

**Comment by pranav-js** [comment]
I thought i was doing something wrong. can we get some attention to this please

**Comment by jetersen** [comment]
Haven't been able to reproduce. Would appreciate a repro repo.

**Comment by rajeshreeputra** [comment]
@jetersen please find the repo, release drafter creating empty releases. Here releases are published from 2 branches master(2.x releases) and 1.x(1.x releases)

https://github.com/acquia/drupal-recommended-project/releases

**Comment by shadycuz** [comment]
@jetersen My recent release was empty https://github.com/DontShaveTheYak/cf2tf/releases/tag/0.5.0

The draft always looks great and then when I change it from draft to a real release its empty. 

```
release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [tag, publish]
    steps:
      - name: Create Draft Release
        uses: release-drafter/release-drafter@v5.23.0
        if: github.base_ref == 'develop'
        with:
          tag: ${{needs.tag.outputs.tag}}
          version: ${{needs.tag.outputs.tag}}
          commitish: develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: release-drafter/release-drafter@v5.23.0
        if: github.base_ref == 'master'
        with:
          tag: ${{needs.tag.outputs.tag}}
          version: ${{needs.tag.outputs.tag}}
          publish: true
          commitish: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Here is the job output https://github.com/DontShaveTheYak/cf2tf/actions/runs/4506018650/jobs/7932384277
