### ISSUE TITLE
[Question] Is it possible to change the target branch of the drafted release?

### ISSUE THREAD

**Issue by malimccalla** [release-drafter/release-drafter#884]
Hi, I have this basic config set up:

```yaml
 # Drafts our next Release notes as Pull Requests are merged into "master" 
 - name: Release Drafter
   uses: release-drafter/release-drafter@v5
   env: GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 ``` 

On this project, the default branch is `staging`. However, when releases are created we need to release them from the `master` branch. By default when the release drafted it points to `staging` as it's our default git branch. This can be problematic as it's easy to forget to change the dropdown from `staging` to `master` before deploying, Is there any way to change this target value in the config?

<img width="528" alt="Screenshot 2021-06-04 at 19 00 48" src="https://user-images.githubusercontent.com/18899991/120847262-25b93780-c56b-11eb-8254-9a934394ff68.png">

**Comment by jetersen** [comment]
Yes https://github.com/release-drafter/release-drafter#action-inputs via `commitsh`

```yaml
  - name: Release Drafter
    uses: release-drafter/release-drafter@v5
	with:
	  commitsh: staging
    env: GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
