### ISSUE TITLE
[Bug] Null exception when body regex is set but PR description is empty

### ISSUE THREAD

**Issue by frundh** [release-drafter/release-drafter#968]
Autolabeler with a body regex like this:
```yaml
autolabeler:
  - label: 'bug'
    body: ['/foobar/']
```
will cause a null exception if the PR body is empty
```
TypeError: Cannot read property 'match' of null
```
