### ISSUE TITLE
How to use autolabeler to label PR automatically?

### ISSUE THREAD

**Issue by fjchen7** [release-drafter/release-drafter#980]
What I want is
- Label PR automatically when detecting PR is opened, reopened or synchronize
- Draft release when pushing tag

Here is my configuration

`.github/workflow/drafter.yml`
```yml
on:
  push:
    tags:
      - 'v*'
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  release_drafter:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ env.RELEASE_VERSION }}
          # only draft release when pushing tag
          disable-releaser: ${{ github.ref_type == 'branch' }}
          # label PR
          disable-autolabeler: false
```

`.github/release-drafter.yml`

```yml
autolabeler:
  - label: 'chore'
    files:
      - '*.yml'
    branch:
      - '/docs{0,1}\/.+/'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'

name-template: '$RESOLVED_VERSION'
template: |
  $CHANGES
category-template: '## $TITLE'
#  omitting...
```

In a newly opened PR where I update `.github/release-drafter.yml`, workflow run successfully but label `chore` is not added. I can make sure that the label `chore` has existed already in label list. And I also test with branches matching the regex condition in `.github/release-drafter.yml`. However no label is added as well.

Can someone give an example about autolabler and show me how to add label automatically in PR? Very thanks!
