### ISSUE TITLE
autolebler fails to label PR when PR is edited

### ISSUE THREAD

**Issue by fjchen7** [release-drafter/release-drafter#990]
Here is my configuration

```yaml
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  add_label_on_PR:
    runs-on: ubuntu-latest
    steps:
      - name: Add label on PR
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          disable-releaser: true
          disable-autolabeler: false
```

What I did
1. Fork and then submit a new pull request. Label is added by release-drafter as expected.
2. Unlabel manually.
3. Make change on body which won't affect label regex match.
4. Then release-drafter will be triggered again.
5. After job is done, nothing happens. No label is added.

No error is reported in action running log. 

I have test other pull request event
- `opened` (create new PR)
- `repoened` (close and then repoened)
- `synchronize`(submit and push new commit to forked branch)

All works well. Does autolebler does not support event expect these three ones?
