### ISSUE TITLE
regex in autolabeler does not work

### ISSUE THREAD

**Issue by fjchen7** [release-drafter/release-drafter#992]
I have the configuration

```yaml
autolabeler
  - label: 'bug'
    branch:
      - '/fix\/.+/'
      - '/(bug|bugfix|fix|hotfix)\/.*/'
    title:
      - '/^bug.*/i'
```

For different PR title in test:
- `bug xyz`: no label added
- `^bug.*`: label added
- `^Bug.*`: no label added

As far as I see, regex does not work at all. It match exact text and won't translate `^`, `.`, `*` or `/i`
